### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by CupOfTea696** [jekyll/jekyll-assets#151]
I'm trying to get sourcemap working, but so far I've got no luck

in my `_plugins/jekyll-assets.rb`:

``` ruby
require "jekyll-assets"
require "yui/compressor"
require "sprockets/sass"
require "autoprefixer-rails"
require "sprockets/sass/functions"

Sprockets::Sass.options[:style] = :compressed
Sprockets::Sass.options[:sourcemap] = :auto
```

**Comment by envygeeks** [comment]
I think this may need to wait for Sprockets 4.x which I believe is due sometime this year.

**Comment by leiming** [comment]
+1, I want to use sourcemap in development environment.

**Comment by envygeeks** [comment]
We support SourceMaps in 3.x.
