### ISSUE TITLE
Clean previously generated assets when regenerating

### ISSUE THREAD

**Issue by lvonk** [jekyll/jekyll-assets#154]
Hi,

Is it possible to configure jekyll-assets in such a way that it cleans previously generated assets when the assets gets regenerated by for instance `jekyll serve`? Currently the `_site` directory is filling up with no longer used assets. Restarting `jekyll serve` does clean the entire directory. 
See https://github.com/jekyll/jekyll/issues/3742.

**Comment by j15e** [comment]
I found this issue too & made a quick workaround, but I need to do some additional work before having clean pull request. In the meantime you can have a look at my commit here https://github.com/didacte/jekyll-assets/commit/3d1ace7cadd380afda28bf5b0503197eda716299 which add a fix to avoid removing assets on empty rebuild.

**Comment by envygeeks** [comment]
Is this still the case on 2.0.0 alpha?

**Comment by envygeeks** [comment]
This issue has been open for more than 2 weeks without a response, it is being closed.  If there is a change in circumstance please ask for this ticket to be reopened answering the questions posed.
