### ISSUE TITLE
Provide asset tag in v2.0.0

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-assets#182]
I’ve just been trying out the beta of 2.0, and it looks to be shaping up to a nice update. However, the one tag I make fairly heavy use of with the current version is `{% asset %}`. Here are two use cases…

## Inlining CSS and JavaScript
To implement inlining critical CSS on first page load (see: https://github.com/filamentgroup/loadCSS), I use the following template:

```
<!DOCTYPE html>
<html lang="en-gb">
<head>
    <title>{{ if page.title }}</title>
    <meta charset="utf-8"/>
    <meta name="fullcss"  content="{% asset_path global.css %}">

<!--#if expr="$HTTP_COOKIE=/fullcss\=true/"-->
    <link rel="stylesheet" href="{% asset_path global.css %}"/>
<!--#else-->
    <style>
        {% asset critical.css %}
    </style>
<!--#endif-->

    <script>
        {% asset head.js %}
    </script>
    <noscript>
        <link rel="stylesheet" href="{% asset_path global.css %}">
    </noscript>
</head>
```

Note also that am I using `{% asset %}` to inline a small snippet of JavaScript that appears in the `<head>` of every document too.

## Inlining SVG
I also use `{% asset %}` to inline SVG artwork, the path to which I provide in the plugin config. For example:

```
<header class="c-banner u-container" role="banner">
    <h1 class="c-banner__title">
        <a class="c-banner__home" rel="home" href="/" tabindex="1">
            {% asset c-banner__logo.svg %}
        </a>
    </h1>
</header>
```

This ensures all my SVG files are located in one folder, and alongside other assets.

## Why not just use the include tag?
* Using the `{% include %}` tag means placing some assets inside the _includes folder, some inside my _assets folder, which becomes a bit of a disorganised mess! (And in effect, all assets need to live inside the includes folder)
* The `{% include %}` tag requires the full path to the asset; what I love about `jekyll-assets` is that I don't need to do that, which gives me additional flexibility.
* Also — and I haven’t tested this yet — given that my Sass file needs to be compiled before being included, I’m not sure whether the raw or compiled CSS will be output using the `{% include %}` tag.

I hope I’ve made a good case for the return of the `{% asset %}` tag, but please ask if you need more info.

**Comment by envygeeks** [comment]
That is what you wanted yes?

**Comment by envygeeks** [comment]
If it's not what you wanted then please do let me know with further clarification and I'll try again!

**Comment by paulrobertlloyd** [comment]
Wow, that was fantastically quick, thanks! Yep, this is exactly what I was looking for.

I will note one (minor) behavioural change; in the previous version of the plugin, only linked assets where generated; now, even in an asset is only asset_source inlined, the file is still generated. It’s a small thing, but thought it was worth noting.

I also have some follow on questions, but as these relate to separate things, I’ll open new issues for them.

Thanks again!

**Comment by envygeeks** [comment]
If they are generic questions that aren't bugs or feature requests it's best to ask them at https://talk.jekyllrb.com.  As for the second paragraph I'm a bit confused, can you elaborate or clarify it a bit more?

**Comment by paulrobertlloyd** [comment]
Okay, happy to start a thread in that forum.

As to the other issue, take the following (simplified) template markup:

```
<!DOCTYPE html>
<html lang="en-gb">
<head>
    <style>
        {% asset_source critical.css %}
    </style>

    <link rel="stylesheet" href="{% asset_path global.css %}">
</head>
```

In v1 of the plugin, this would result in the following files being generated:

```
assets/
- global.css
```

In v2 of the plugin, the following files are generated:

```
assets/
- critical.css
- global.css
```

Further, it seems the plugin no longer cleans the assets directory before writing new files. Previously, running a development build, and then a production build, the following files would be generated:

```
assets/
- global-[#HASH].css
```

With v2, the following files are generated:

```
assets/
- critical.css
- critical-[#HASH].css
- global.css
- global-[#HASH].css
```

Note, that only one of these four files is actually required. Does that help?

**Comment by envygeeks** [comment]
We do not generate non-digested next to digested, we generate one or the other: 
1. https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L94
2. https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/env.rb#L120-L124
The non-digested being next to the digested is not by us, it's by something else.

On the other issue, file a unique ticket and ask that asset source not add the asset to sprockets.used Set we create to track what files to write: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/tag.rb#L68  that's a unique problem that is a regression, as earlier versions of 2.0.0 did not do that but it was recently changed by a pull as I did not see any harm in it but I can add a helper on  the class to track the tag type and reject adding it unless something else that needs it includes it.

**Comment by amw** [comment]
I've moved that `sprockets.used` call before the conditionals so that it gets called for `asset_path`. Now that `asset_source` is there I think we need to add special cases. It doesn't make sense to mark file as used when it's included inline.
