### ISSUE TITLE
Enable use of asset_path within Sass files

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-assets#185]
This the following example:

Config:

```
assets:
  sources:
    - _assets/fonts
    - _assets/stylesheets
```

File structure:
```
assets/
  fonts/
    calibre-regular.woff
  stylesheets/
    webfonts.scss
```

Sass:
```
// webfonts.scss
@font-face {
    font-family: 'Calibre';
    font-weight: normal;
    font-style: normal;
    src: url(asset_path('calibre-regular.woff')) format('woff');
}
```

calibre-regular.woff *is not* generated. If I create the following HTML:

```
<!-- test.html -->
<link href="{% asset_path calibre-regular.woff %}">
```

calibre-regular.off *is* generated.

You can see a fuller implementation here: https://github.com/paulrobertlloyd/paulrobertlloyd.com

Is this something I need to enable somehow?

**Comment by envygeeks** [comment]
This is not a regression 2.0 is a major version with it's own specifications and it's a complete rewrite with no promise of backwards compatibility.  Yes, I've gone out of my way to try and make the pain less noticeable but anything not included or different is on a case-by-case decided as a bug or a future feature.

**Comment by paulrobertlloyd** [comment]
Okay, I understand that (and agree with keeping features more scoped than in the previous version). Perhaps ‘regression’ was too overloaded a term. But anyway, it was a *really useful* feature, that is no longer available. :-)

**Comment by envygeeks** [comment]
Show me the list of files in that folder after you generate the site and it doesn't work.

**Comment by paulrobertlloyd** [comment]
Ah, okay, I think I see what’s going on here. This is a different (smaller) bug.

I’ve been running the following command, where I would delete my destination folder, and initiate a full-rebuild:

```
rm -rf [destination_folder]
JEKYLL_ENV=production bundle exec jekyll build --full-rebuild"
```

What I think is happening here, is that the cache for Jekyll Assets doesn't take account for the full-rebuild, assumes certain files are still present, and doesn’t generate them (why this is limited to those reference in Sass files, I’m unsure). As a short term fix, I’ve removed the (probably unnecessary, and only recently introduced) `rm -rf` step in my build workflow.

Have I uncovered a bug here? Does Jekyll Assets already know if a full-rebuild is taking place?

**Comment by envygeeks** [comment]
We don't care whether or not you are doing a full rebuild or not as we work independently of that system.  We only tie into one specific spot and that is letting Jekyll know that we have a tag that might have an asset that might change and if it does, it needs to act accordingly to how it sees fit outside of our system and this only matters if you have enabled digesting, otherwise we ignore incremental regeneration entirely.

Provide full reproduction steps that I can copy and past and I will enable debugging on my end and see if this is a bug in our system.

**Comment by envygeeks** [comment]
I'm asking for complete copy and paste mostly because I don't quite understand how this is happening as we go out of our way to double check if we need to write so if I can get a copy and past to rerun over and over I can step over my context.  So much appreciated!
