### ISSUE TITLE
Image sizes are gone

### ISSUE THREAD

**Issue by swernerx** [jekyll/jekyll-assets#192]
We made some major amount of use of the "autosize" feature in the previous version. Unfortunately all this code seems to be gone now. Using the old 1.x jekyll-assets works okay for Jekyll-3 as it seems, but upgrading would still be better IMHO. Unfortuntely I cannot figure out an easy way of adding the same feature again.

What I basically need is an "autosize" config setting which automatically adds the image sizes to the img-tags produced by Jekyll. Anything like this on your roadmap? Thanks!

**Comment by envygeeks** [comment]
This is something that can be facilitated before the final release this week.

**Comment by swernerx** [comment]
Perfect! Can't wait!

**Comment by gasparesganga** [comment]
I'm not sure if this is a direct consequence of this change, but it is now happening something that in version 2.0.0.pre.beta was not: by default some `width`, `height` and `alt` html tags are attached to every image.
The result is the same with both `{% image src %}` tag and `{{ src | image }}` filter:
`<img src="src" alt="src" width="xxx" height="yyy">`

Is there a way to disable those *(maybe like @swernerx proposed, some kind of config option)* and produce a plain:
`<img src="/path/to/file.jpg">`
without any additional html tags?

**Comment by envygeeks** [comment]
@gasparesganga at this time there isn't but if you file a uniq ticket (if you already haven't) I'll be happy to add one for you so you can disable all our automatic stuff.
