### ISSUE TITLE
Cachebusting in jekyll-assets 3?

### ISSUE THREAD

**Issue by Rio517** [jekyll/jekyll-assets#194]
I noticed that cache-busting seems to have been removed in the latest versions of jekyll-assets.  Is that a capability you wont be supporting any longer?

Initially added from: https://github.com/jekyll/jekyll-assets/issues/11

**Comment by envygeeks** [comment]
Cache busting is unnecessary because Sprockets 3.0 tracks all assets that you use and busts it themselves as they see fit using a much more robust algorithm that we would use (or did use.) We have no plans to cache outside of sprockets as it increases complexity for very little benefit.

If you are having problems with assets not refreshing without a digest please file a ticket on `jekyll/jekyll` and @jekyll/core will happily consider adding a default header (though I recall that recently being brought up and fixed? I might be wrong though it might have been for another header.)

If you wish to enforce a digest you can however do that in the meantime, just send digest: true and we will respect regardless of what JEKYLL_ENV we detect and do as you wish.  If you wish to disable caching entirely you can also do that by just doing "cache: false" because our code explicitly checks if the value even exists and will only trip on true or non-string but will disable itself on nil or false.

**Comment by Rio517** [comment]
This some background and a way to soft cache for those who need it. In my case,  hard cached file names won't work if I'm trying to reference a css file from our tumblr blog theme. On every deploy the fingerprint for all static assets changes (app-lakdsjflake.js).  

**Background:** Basically sprockets dropped support for soft caching in the most recent version.  You can either digest all assets and hard fingerprint your files or not at all.  There was a heated discussion about it in github issues (I misplaced the link), and eventually the core team agreed they want to re-add soft caching at some point.  

## Work around

Until then, here is a work around, I wound up implementing my own soft caching in jekyll 3.0 with the following custom hooks.

* you'll need to add uglifier to your gem file `gem 'uglifier'`
* `_plugins/cache_bust_filters.rb` - adds filters for generating soft cached reference urls *.css?md5_hash
* `_plugins/uglifier.rb` - manually compress and gzip js (causes issues on jekyll serve, use env to get around). 
* `_plugins/env.rb` - manages environment variables so we only compress/minify js on production environments.
* You'll need to build your production jekyll assets w/ `JEKYLL_ENV=production jekyll build`

### _plugins/cache_bust_filters.rb
```ruby
# Note: Github doesn't allow plugins to execute (safemode). These filters won't work on github pages.
module Jekyll
  module CacheBustFilters
    # A simple class to handle md5 hexdigesting
    # Initializing params:
    # * file_name - String - required - this is both filename to which the md5 
    #   hash will be appended to, and will be read for hexdigest in the absence
    #   of a passed in directory.
    # * directory - String - optional - path of directory files that will be
    #   recursively read and passed into hexdigest
    class CacheDigester
      require 'digest/md5'

      attr_accessor :file_name, :directory

      def initialize(file_name:, directory: nil)
        self.file_name = file_name
        self.directory = directory
      end

      def digest!
        [file_name, '?', Digest::MD5.hexdigest(file_contents)].join
      end

      private

      def directory_files_content
        target_path = File.join(directory, '**', '*')
        Dir[target_path].map{|f| File.read(f) unless File.directory?(f) }.join
      end

      def file_content
        FIle.read(file_name)
      end

      def file_contents
        is_directory? ? file_content : directory_files_content
      end

      def is_directory?
        directory.nil?
      end
    end

    # Gets Md5 contents of target file (assumed to be using the full path)
    # and appends a hash end of to asset file reference. Ensures deployed
    # asset files are "cachebust-ed" every time the file changes
    def md5_cache_bust(file_name)
      CacheDigester.new(file_name: file_name).digest!
    end

    # Gets Md5 contents of all sass assets (assumed to be in /_sass/ )
    # and appends a hash end of the target asset file. Ensures deployed
    # sass based CSS files are "cachebust-ed" every time the files change
    def sass_cache_bust(file_name)
      CacheDigester.new(file_name: file_name, directory: '_sass').digest!
    end

    # Gets Md5 contents of all js assets in _assets/javascripts/
    # and appends a hash end of the target asset file. Ensures deployed
    # files are "cachebust-ed" every time the files change. Using
    # jekyll-assests requires first capturing the asset_path string, and
    # passing the path to this filter in a subsequent liquid call.  Example:
    #    {% capture asset_path_string %}{% asset_path app %}{% endcapture %}
    #    <script type="text/javascript" src="{{ asset_path_string | js_cache_bust }}"></script>
    def js_cache_bust(file_name)
      file_name.gsub!('.js','.min.js') if ENV['JEKYLL_ENV'] == 'production'
      CacheDigester.new(file_name: file_name, directory: '_assets/javascripts').digest!
    end
  end
end

Liquid::Template.register_filter(Jekyll::CacheBustFilters)
```

### _plugins/uglifier.rb
```ruby
# After build uglifier
#
### WHY
# Sprokets won't allow us to digest our js and use custom
# cachebusting or fingerprinting of our files.  In order
# to allow third party services to fetch our files, we need
# assets available at stable urls - we need: app.js?xxx not
# app-xxx.js to be generated.
#
### SOLUTION
# We turn off digesting in sprokets, use a plug to create a
# custom md5 cachebusting cache, and use this plugin to
# minify assets after writing the site
if ENV['JEKYLL_ENV'] == 'production'
  Jekyll::Hooks.register :site, :post_write do |post|
    require 'uglifier'

    target_assets = Dir.glob('_site/assets/*').select {|f| File.file?(f)}
    target_assets .each do |file|
      minified_file = Uglifier.new.compile(File.read(file))
      minified_file_name = file.gsub!('.js','.min.js')
      puts 'Minfiying js manually...'
      File.open(minified_file_name, 'w') do |file|
        file.write(minified_file)
      end
      puts 'Gzipping js manually...'
      Zlib::GzipWriter.open(minified_file_name + '.gz') do |gz|
        gz.write minified_file
      end
    end
  end
end
```


### _plugins/env.rb
```ruby
class Jekyll::Site
  attr_accessor :env
end

class Env < Jekyll::Generator
  priority :highest
  def generate(site)
    site.env = ENV['JEKYLL_ENV'] || 'development'
    puts "Building w/ #{site.env} environment"
  end
end
```

**Comment by envygeeks** [comment]
@Rio517 I'm happy to accept this directly into Jekyll Assets if you want to form it as a pull for review!

**Comment by ellisonch** [comment]
After hearing about jekyll-assets from a number of places, I was really looking forward to using the hashed-content cache busting feature.  It seemed like I would be able to add the gem to my site and change some of my liquid templates and jekyll would take care of everything.  I'm really sad to see this feature removed.

At least, I assume it's been removed based on it no longer being mentioned on the main page.  My confusion comes from trying to read through this issue.  I have never heard of sprockets before this thread, but it seems to be some kind of ruby library/webserver.  Based on the conversation above
> Sprockets 3.0 tracks all assets that you use and busts it themselves

this sounds like a dynamic thing, so it seems you are now assuming your users will be using sprockets as their web server.  I use jekyll because I want to generate a static website with no runtime dependencies.  Perhaps there is a way to use jekyll-assets to tell sprockets to generate the hashes statically, or perhaps that's what @Rio517's workaround code does.

Considering I'm new to jekyll-assets, I'm probably misunderstanding the issue, so please let me know where I'm confused.  It's also been more than a year since this issue was filed, so I'd love to know what you suggest now.  Thanks!

**Comment by Rio517** [comment]
Sprockets is a gem (ruby library) for asset management/compilation that is a part of rails and generally a cornerstone of the ruby ecosystem. It is common in the ruby world to build upon existing libraries rather than reimplment similar fuctionality. Jekyll-assets depends on sprockets, so yes, users of this gem will be using sprockets.  

While soft cache busting was removed, it was removed from sprockets, not jekyll-assets. While restoring soft cache busting/fingerprinting seemed to be on the radar for sprockets 4, I can see no mention of it looking through their github repository. 

Your options are:
* disable cache digesting completely
* use my work around
* get in touch with sprockets team and get them to support to soft cachebusting (or add it yourself in a fork).
* or maybe try to find a fork of sprockets that has this soft cachebusting/fingerprinting.

Jekyll is a static site generator, so obviously there are no runtime dependencies other than a webserver capable of serving static files (basically, all of them).  The output is just static html.

**Comment by ixti** [comment]
I did not found discussion as well. But I don't see any problems in adding soft-caching on jekyll-assets. Jekyll-assets is a wrapper on top of sprockets, and it works with `Sprockets::Assets` internally when it generates links in [url helpers](https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/helpers.rb#L13-L25). `Asset#digest_path`is simply logical path with hexdigest (etag) injected in. So for soft-cachebusting all that is needed:

``` ruby
"#{asset.logical_path}?cb=#{asset.hexdigest}"
```

**Comment by Rio517** [comment]
Oh cool @ixti. I didn't notice that before.  I haven't had this need in a while, but I was under the impression that the build process would write files  asset-[fingerprint].js without generating the files at the logical path unless one disabled asset digests.   If this also minifies and gzips assets, then this could be a great solution.

**Comment by ixti** [comment]
@Rio517 oh. I was not hacking on sprockets for quiet some time now, so I believe I probably misunderstood the initial problem. Or at least it needs second part ;))

I assume (now) that you are refering that `Sprocekts::Manifest` records digested (hard cache busted) assets only. If so, then this is how e solved this problem at SensorTower:

``` ruby
module Sprockets
  class Manifest
    module NonDigestFiles
      def compile(*args)
        filenames = super

        assets.each do |logical_path, digest_path|
          digest_path   = File.join(dir, digest_path)
          logical_path  = File.join(dir, logical_path)

          # This probably should not happen with "real" files, but it can at least with silly ones, e.g.
          #   `app/assets/javascripts/Find Results`.
          next if digest_path == logical_path

          copy_asset(digest_path, logical_path)

          digest_path << ".gz"
          logical_path << ".gz"

          copy_asset(digest_path, logical_path)
        end

        filenames
      end

      private

      def copy_asset(digest_path, logical_path)
        return unless File.exist? digest_path

        File.open(digest_path, "rb") do |src|
          File.open(logical_path, "wb") do |dst|
            IO.copy_stream(src, dst)
          end
        end
      end
    end

    prepend NonDigestFiles
  end
end
```

**Comment by alexandre1985** [comment]
Is soft cache bust implemented?
If yes, can someone tell me how to use it successfully?
Thank you
