### ISSUE TITLE
Allow use of magick with asset/asset_path/asset_source

### ISSUE THREAD

**Issue by mshick** [jekyll/jekyll-assets#199]
If I need to use the modified image in something other than an `<img>` tag (say, `<link>` href for favicons, building my own srcset) this would be quite useful.

**Comment by envygeeks** [comment]
This should be possible but It'll have to wait until 2.1 because I'm already running late on the final 2.0 final, once 2.0 is final 2.1 should come pretty quickly though so you won't have to wait too long... just as long as it takes me to clear my backlog again.

**Comment by mshick** [comment]
@envygeeks makes sense, looking forward to the release.

For anyone interested, I put together a simple plugin that provides a filter for this functionality. It leverages `jekyll-assets` and some `nokogiri` parsing to provide an asset path for a proxy-processed image.

Here's the gist: https://gist.github.com/mshick/a2192aa621026c5c9a72

**Comment by envygeeks** [comment]
This is shifting to 2.2 because 2.0.2 ended up being 2.1 because of a needed API change.

**Comment by ikus060** [comment]
For those who need this feature quickly, I've create a small plugin to extend jekyll-assets.

imagepath.rb
```
require "jekyll-assets"

class Jekyll::ImagePath < Jekyll::Assets::Liquid::Tag

  def initialize(tag, args, tokens)
    super("img", args, tokens)
  end

  private
  def build_html(args, sprockets, asset, path = get_path(sprockets, asset))
      path
  end

end

Liquid::Template.register_tag('image_path', Jekyll::ImagePath)
```

Usage:
```
{% image_path "markdown.png" magick:resize:106x75^ %}
```

Output:
```
/assets/markdown-757a1b9d2cf8395d2a7b379107b9a9cc388987a5306643e0e95ffb23320929cb.png
```

**Comment by 2474** [comment]
@ikus060, I'm pretty new to Ruby so I was wondering if you could explain why your plugin wouldn't work with:

```
{{ 'markdown.png' | image_path: 'magick:resize:200x200' }}

Thanks!
```

**Comment by ikus060** [comment]
Simply put, the plugin only implement tag not filter. So on tag is supported. I don't have plan to implement filter. It was a quick and dirty way to work around limitation of Jekyll asset.

**Comment by funkenstrahlen** [comment]
@ikus060 Thank you for your workaround! Works fine.

```ruby
  class JSONGenerator < Generator
    priority :lowest
    safe true
    
    def generate(site)
      // use it here?
    end
end
```

Is there any way I can access the liquid template code inside a Generator?

**Comment by joshreeves** [comment]
Any ETA on this feature? It would be highly useful.

**Comment by ShintaroNippon** [comment]
Hello
when you get the 
Output:

/assets/markdown-757a1b9d2cf8395d2a7b379107b9a9cc388987a5306643e0e95ffb23320929cb.png

it is possible get output only assets/markdown.png

Thanks in advance
Carlos Vieira

**Comment by mattbeedle** [comment]
@ShintaroNippon Isn't that what the `asset_path` helper does?

**Comment by envygeeks** [comment]
`asset_path` and `asset_source` have been removed in 3.x so this feature will not happen unfortunately.  It is however supported with `{% img name @path magic:argument=val %}` where we proxy and then do logic to determine if we should throw out source, path or html.

**Comment by envygeeks** [comment]
3.x will be released this week.  Sorry for not mentioning that.

**Comment by ygd** [comment]
@envygeeks as asset_path/ass_source is removed in v3 how do we load favicons in link tag?

**Comment by envygeeks** [comment]
Please read the documentation, it says inside of the documentation how to achieve what you wish.

**Comment by ygd** [comment]
oh, yeah. sorry. didn't actually look close enough to the arguments table:

maybe it helps for listing in search results …
```<link rel="shortcut icon" type="image/x-icon" href="{% asset favicon @path %}">```

**Comment by envygeeks** [comment]
If I did that the documentation would never end, we list basic examples only, the rest of it only gives you the possibilities.  That said you don't need all that to get Favicons, just do `{% asset favicon %}`, we build the favicon link tag for you.
