### ISSUE TITLE
SASS syntax causing Liquid error

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll-assets#206]
The first lines of my `main.scss` file are as follows:

```
@charset "utf-8";
@import 'fonts';
@import 'bourbon/bourbon';
@import 'neat/neat';
...
```

The `main.scss` file is in `_assets/css` and being included in `head.html` using `{% stylesheet main %}`.

I'm getting the following error when building my site.

`Liquid Exception: Invalid CSS after "@charset "utf-8"": expected "{", was ";" (in /Users/charlie/GitHub/jekyll-test/_assets/css/main.scss:4) in _includes/head.html, included in _layouts/default.html`

Is it possible to resolve this?

**Comment by envygeeks** [comment]
If this is a bug it' an upstream bug.  We don't read your source and we don't process it, that's done by Sprockets so if this is a bug it's happening there.   The only sources we actually touch and wrap are images and that's *after* sprockets touches and does what it needs with your source.

**Comment by charliesneath** [comment]
Is Sprockets already included in `jekyll-assets`, or do I need to add `gem 'sprockets'` to my project?

**Comment by envygeeks** [comment]
Sprockets *is the core* of `jekyll-assets` there is no `jekyll-assets` without Rails Sprockets.

**Comment by charliesneath** [comment]
This is being resolved with https://github.com/jekyll/jekyll-assets/issues/208.
