### ISSUE TITLE
Without ERB support, asset_path in .js files?

### ISSUE THREAD

**Issue by iphoting** [jekyll/jekyll-assets#214]
Hi,

In jekyll-assets v1, I used to have erb pre-process my .js files to render `asset_path()` into my jQuery backstretch plugin / functions for background image manipulation.

Now in v2 that erb support has been removed, is there a way to get image `asset_path()` within a .js file?

Thanks!

**Comment by envygeeks** [comment]
Yes there if you switch to master (HEAD) @iphoting, in master we support processing with Liquid so you'll be able to run your files through liquid and get the asset with `{{ asset_path asset }}`, it's being released with 2.1 but several people are using it in production right now (including me.)

**Comment by iphoting** [comment]
I tried the master version, in Gemfile:
```Gemfile
gem 'jekyll-assets', :github => 'jekyll/jekyll-assets'
```

I renamed the `.js.erb` file to just to end with `.js`.

Here's the snippet of the js source:
```js
$.backstretch("{{ asset_path bg-1200-paper2.jpg }}", {fade: 150});
```

Here's the generated .js:
```js
$.backstretch("{{ asset_path bg-1200-paper2.jpg }}", {fade: 150});
```

I've also tried with `{% asset_path bg-1200-paper2.jpg %}` but I don't see the difference. Are there any switches that I need to tweak to turn on Liquid processing?

**Comment by envygeeks** [comment]
There isn't anything special you need to do as we trigger as a pre-processor on Sprockets,  is there a repo for the source I can use to create a test-case and see if we have the right types.

**Comment by iphoting** [comment]
Thanks for looking into this, I've trimmed down the repo and pushed a copy to <https://github.com/iphoting/jekyll-debug> and added collaboration access for you to play with it.

Hope this helps! 😀

**Comment by envygeeks** [comment]
Thanks for providing a `debug-repo`, it is no longer necessary and you can delete if you do not need it.  This issue should be resolved now, thanks for the report!
