### ISSUE TITLE
Browserify support

### ISSUE THREAD

**Issue by dmitriiivashko** [jekyll/jekyll-assets#215]
Is there any way to have browserify support with jekyll-assets?

**Comment by envygeeks** [comment]
I'm gonna be honest, I don't know what that is, I do systems and backends and I built and maintain this for a front-end lady I know, that's the only reason I took over this project.  If you tell me what it is and how it works I can tell you whether or not it's an upstream problem or whether I can implement it, or whether or not it will work out of the box.

It would also be nice to hear what it is compared to bower.

**Comment by dmitriiivashko** [comment]
http://browserify.org/

It's a very popular module / dependency management for JS.
Instead of concatenating all JS files and having endless fun with bower packages, you can do things like: `var $ = require('jquery')` and have jquery installed with npm. Browserify will bundle it into a single JS file for you. Basically the idea is to bring over the commonjs module management from nodejs world to the browser world. This lib proved itself to be extremely useful and is super popular nowadays.

How it works: it can be both executed from command line (pointing at the main JS file) or be used as a converter stream lib. There are implementations for rails and sprockets, but since I'm a java/js/c guy it's gonna take me forever to see how those are implemented

**Comment by envygeeks** [comment]
Link me to the Rails and Sprockets, more than likely I can just add one of those and it will work as is, considering we have kept our API minimal to do things like that (90% of our addons are all done that way, simply just using the Rails addon.)

**Comment by caspervonb** [comment]
https://github.com/browserify-rails/browserify-rails

**Comment by envygeeks** [comment]
Thanks @caspervonb I looked at  the source and it might be possible to use it and ease the pain but if it isn't it looks like it doesn't actually take much work to get support for it if I have to do it myself as that's not an overly complicated library.

**Comment by nakoo** [comment]
+1. I hope it would be applied.

**Comment by envygeeks** [comment]
Sprockets 4.x and 3.x of Jekyll-Assets will support this.  You should be able to add it to your paths and Sprockets recognize it.  I know it supports NPM and Yarn as well.

**Comment by morungos** [comment]
Any update on this or on 3.x? I could use this.
