### ISSUE TITLE
Unable to ignore .asset-cache* files with .gitignore

### ISSUE THREAD

**Issue by charliesneath** [jekyll/jekyll-assets#217]
Git is picking up changes in the .asset-cache folder, despite `.asset-cache*` being included in `.gitignore`.

Is this a problem with my repo, or something related to `jekyll-assets`?

**Comment by envygeeks** [comment]
It should be `/.asset-cache` in your Gitignore.

**Comment by envygeeks** [comment]
To add, we don't alter your Git or mess with your Git at all so it would ultimately be a git configuration problem or a Git but (more than likely in this case a configuration problem.)

**Comment by charliesneath** [comment]
Fixed, was a problem with repo as you correctly assumed.

Running `git rm -r --cached /.asset-cache -r` seems to have resolved it so far.
