### ISSUE TITLE
How to prevent liquid parsing for some file?

### ISSUE THREAD

**Issue by bianjp** [jekyll/jekyll-assets#223]
If a javascript file contains '{%' but is not valid liquid syntax, `jekyll build` fails with `[something] was not properly terminated with regexp: /\%\}/`.

To reproduce it:
1. create a test.js file in your javascript assets folder
2. add `var a = '{%';` to the file
3. include it in any html file with `{% js test %}`
4. run `jekyll build`

I meet the problem since I'm using [highlight.js](https://github.com/isagalaev/highlight.js), and its js contains '{%'.

I want to merge all js files into a single file, so I don't want to manage highlight.js outside jekyll-assets.

Any way to prevent jekyll-assets from parsing some js file?

**Comment by envygeeks** [comment]
At this time there is no way to do it easily, you can wrap the entire file in a {% raw %} tag though and it won't process it, I'll see if there is a viable way to allow something like "raw.js" and "raw.scss" to prevent our processing in the future though.

**Comment by bianjp** [comment]
Thanks.
I just updated highlight.js and was happy to find that it no more contains '{%' (the reason may be that I didn't choose those languages that has '{%').

Jekyll-assets is a great project. Thanks for your work.

**Comment by sankage** [comment]
This is also occurring for `{{ }}`.

I am using Cycle2 for an image slideshow and it has [this template regex](https://github.com/malsup/cycle2/blob/master/src/jquery.cycle2.tmpl.js#L6 it uses:

```javascript 
    tmplRegex: '{{((.)?.*?)}}'
```

Once built, that value becomes 

```javascript
    tmplRegex: ''
```

Which doesn't return any errors during the build phase, but does have complications when the javascript runs.

**Comment by aaronbski** [comment]
I was getting this error as well with another JS library. I have the liquid option set to false (the default, I believe), so I thought it would not parse any JS or CSS files for liquid templates. Am I wrong about that?

```
assets:
  features:
    liquid: false
```

**Comment by envygeeks** [comment]
@aaronbski yes... unless you are on HEAD.  The documentation in README only applies to head as each released version has a branch with the README for that specific version.  You'll need to set your Gemfile to `:github => "jekyll/jekyll-assets"` until this weekend sometime. I plan on cleaning up the source and releasing a new version since you aren't the first person who asked for this to be released into a stable release.

**Comment by aaronbski** [comment]
@envygeeks Got it. Thanks!

**Comment by envygeeks** [comment]
@sankage @bianjp this issue is fixed with: https://github.com/jekyll/jekyll-assets/commit/7a8981c4cd5c7be02d03c888fd41e60b93b17296 until I release a version this weekend you can use `:github => "jekyll/jekyll-assets`

**Comment by sankage** [comment]
thanks
