### ISSUE TITLE
Issue with Autoprefixer Rails plugin

### ISSUE THREAD

**Issue by nhoizey** [jekyll/jekyll-assets#227]
I had a issue with the Autoprefixer Rails plugin, but the author thinks it's because Jekyll Assets still uses an old API: https://github.com/ai/autoprefixer-rails/issues/81#issuecomment-166874195

I'm still using Jekyll 2, all the plugins I use not being available for Jekyll 3.

My code: https://github.com/nhoizey/nicolas-hoizey.com/

**Comment by ai** [comment]
@envygeeks ping me if you need any help.

**Comment by envygeeks** [comment]
Unfortunately we no longer issue fixes for Jekyll Assets Legacy, it's Sprockets is old (2.0), and all it's plugins are old. AFAIW we do use the new API on current Jekyll Assets (if you could confirm @ai via: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/addons/autoprefixer.rb)

**Comment by ai** [comment]
@envygeeks yeap, looks like new Jekyll Assets uses correct new API.

**Comment by nhoizey** [comment]
So it means I have to keep outdated versions, or migrate to Jekyll 3 but remove obsolete plugins… tricky… :-/

**Comment by nhoizey** [comment]
When I try to force v3.0.1 in my Gemfile:

```
source "https://rubygems.org"

gem "jekyll", '=3.0.1'
gem "redcarpet"
gem "yt"
gem "rouge"

group :jekyll_plugins do
  gem "jekyll-picture-tag"
	gem "jekyll-tagging"
  gem "sass", :require => "sass" # http://stackoverflow.com/a/6191046
	gem "jekyll-assets"
	gem "autoprefixer-rails", "5.2.1.3" # https://github.com/ai/autoprefixer-rails/issues/81
	gem "uglifier"
	gem "jekyll-sitemap"
	gem "jekyll-twitter-plugin"
	gem "jekyll-archives"
	gem "algoliasearch"
end
```

I try to install it with `bundle update jekyll` and I get this error:

```
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In Gemfile:
    jekyll (>= 2.4) ruby

    jekyll-picture-tag (>= 0) ruby depends on
      jekyll (< 4) ruby

    jekyll-assets (>= 0) ruby depends on
      jekyll (~> 2.0) ruby

    jekyll (= 3.0.1) ruby
```

Is it really telling me that jekyll-assets desn't allow jekyll 3?

Sorry, I'm new to gems, bundle, etc.

**Comment by nhoizey** [comment]
Ok, when trying to also force v2.1.2 of jekyll assets, it seems the blocking dependency is fastimage, which is required at '~> 1.8', while [blocked at '~> 1.6.4' by the picture tag plugin](https://github.com/robwierzbowski/jekyll-picture-tag/blob/master/jekyll-picture-tag.gemspec)

I asked them if they can upgrade fastimage: https://github.com/robwierzbowski/jekyll-picture-tag/issues/71

But I will remove this plugin as soon as jekyll assets is able to [deal with responsive images](https://github.com/jekyll/jekyll-assets/issues/172) … ;-)

**Comment by envygeeks** [comment]
Closing this but /cc @envygeks (myself) because we will be forking jekyll-picture-tag into our source in 2.3 to offer responsive images (well we probably won't "fork" it but use it as a reference.)

**Comment by nhoizey** [comment]
Be careful if you use this other plugin as a reference, because it only supports the `<picture>` tag, which is the less useful: https://github.com/robwierzbowski/jekyll-picture-tag/issues/68
