### ISSUE TITLE
Can't get anything in _assets to build

### ISSUE THREAD

**Issue by 2474** [jekyll/jekyll-assets#230]
Hello all,

New to the Ruby world so I apologize for the beginners issue. I've looked around and cannot seem to understand what would be causing it.

For some reason whenever I `jekyll build` nothing in my `_assets` folder gets built to `_site`. I'm sure I am missing something but from some of the example issues I've been reading it looks as if assets should be built alas, no.

My project can be viewed [here](https://github.com/2474/visitors). Any help would be appreciated.

Thanks!

**Comment by envygeeks** [comment]
Hi, at this time I feel this is not a bug in Jekyll-Assets so I must ask that you ask your question at https://talk.jekyllrb.com/ where the larger community (and us contributors) will help you with non-bug issues.  This medium is for bugs only.

Thanks and I hope to see you there.

**Comment by drewish** [comment]
I'm also having problems figuring out how to get this working after trying to upgrade from Jekyll 1 to 3... I think the bugs would be a lack of docs. The readme makes it seem like everything should just work.

**Comment by envygeeks** [comment]
@drewish It does just work, if you actually read the docs.  If there is a problem with the docs it would be more helpful to point out where the problem is, because every problem this case had was already covered in the docs.

**Comment by drewish** [comment]
I definitely read through the docs a few times. I also created a topic on that site with more details. I'm happy to help with docs once I can actually get it figured out.

**Comment by drewish** [comment]
https://talk.jekyllrb.com/t/how-do-you-get-jekyll-assets-to-compile-scss-files/1754

**Comment by envygeeks** [comment]
I know this seems like pushing but ultimately it's not.  The problem you are having is a Sprockets design problem not a Jekyll Assets design problem, and I don't know if I would consider it a Sprockets design problem more than a trait of the way things behave.

I'll download foundation following your instructions in the morning and update your post with directions and then update our documentation to explain these types of problems which normally I would consider known file system issues but if you don't have much experience it can get in your way.

**Comment by envygeeks** [comment]
Let me correct "known file system issues" to known require issues on file systems in languages.

**Comment by drewish** [comment]
Yeah I what's confusing to me is figuring out what's handled by sprockets and what's handled by Jekyll-assets. As well as how to do stuff like pass configuration down to sprockets or down to sass.

**Comment by envygeeks** [comment]
The high level is handled by us, the low level is handled by them and us.

* You tell us where to find your assets.
* We tell Sprockets where to find your assets.
* Sprockets decides how to find them and finds them. We do not interfere.
* We interfere as a man-in-the-middle to digestible paths to provide dynamic proxies and caching.
* Sprockets caches the assets, busts the assets and decides the digest for non-proxies.

At this time we do not allow options to be passed to SASS, I'd be happy to look into doing that for you if you file a separate ticket for that.  I know you can, Rails does it, we should be able to do it too, and I think I've seen that inside of Sprockets.

**Comment by envygeeks** [comment]
The problem you are having, I cannot feasibly explain without trying for myself and stepping into our context to see how Sprockets is behaving.  Once I can do that I can reliably say: "yes we can work around this, I'm going to so your life is easier" or "no we can't work around this easily, but here is a work around and how Sprockets expects it to work."
