### ISSUE TITLE
[REGRESSION] magick:resize: proxies not working

### ISSUE THREAD

**Issue by ikus060** [jekyll/jekyll-assets#235]
With version 2.1.0, magick:resize proxy is working fine. Udating to jekyll-assets in master branch, the proxies are not working anymore. See #234

The images files is properly created at the right location, but the images was not resized by the proxy.

**Comment by envygeeks** [comment]
Hi, I have notified my master (@envygeeks) of this regression and discovered that it is caused by https://github.com/jekyll/jekyll-assets/commit/6c0297873f7acfbccc865b2df50290b3aff940c7#diff-549b461c007403dc7ca284bdb2f3303dR18
