### ISSUE TITLE
How do you add sass style compressed using the asset plugin? 

### ISSUE THREAD

**Issue by arunc** [jekyll/jekyll-assets#236]
Hi, 

I am looking for help on how to minify the css. Here's the config.yml that I am using: 

assets:
  js_compressor: uglifier
  css_compressor: sass
  cache:
  sources:
    - _assets/scss
    - _assets/js
  cachebust: hard

**Comment by envygeeks** [comment]
We no longer support v1.0, please update to 2.0 and read the README. Thanks.
