### ISSUE TITLE
font-awesome-sass fonts are missing in production

### ISSUE THREAD

**Issue by hackhowtofaq** [jekyll/jekyll-assets#239]
Very strange bug 

My gem file

```
gem 'jekyll', '3.0.1'
gem 'jekyll-paginate'
gem 'rake'
gem "uglifier"
gem "sass"
gem 'jekyll-assets'
gem 'font-awesome-sass'
```

my _config.yml

```
...
gems:
  - jekyll-assets
  - jekyll-paginate
```

If `.asset-cache` exists in jekyll main folder (from a previous run)

`JEKYLL_ENV=production bundle exec jekyll build` does not copy the font awesome fonts
in `_site/assets/font-awesome/...` and breaks all icons.

When I `rm -fr .asset-cache` and then `JEKYLL_ENV=production bundle exec jekyll build`
everything works.

Ty

**Comment by envygeeks** [comment]
Very strange (and interesting) indeed and I don't know if we can fix that because we don't control the cache, we defer all that logic off to Sprockets but I'll definitely try to reproduce it so we can see where it needs to be fixed and what actually causes it.

**Comment by ourai** [comment]
It seems that  [font-awesome-sass](https://github.com/FortAwesome/font-awesome-sass/tree/master/assets/stylesheets) caused it.

The structure of it like below:

```
_font-awesome-compass.scss
_font-awesome-sprockets.scss
font-awesome.scss
```

The `font-awesome.scss` should be `_font-awesome.scss`.

**Comment by paulozoom** [comment]
I have a related issue. Since I started building for production, my fonts, **even in development**, stopped being copied over when running `serve` or `build`. Removing `.asset-cache` fixes it.

**Comment by envygeeks** [comment]
Finally got a chance to play with a site that had this problem tonight, this is crazy, I think we might have to hack their stuff to get this fixed, it doesn't add it's path to us at all.  I'll be releasing a fix soon.

**Comment by dramalho** [comment]
It's not clear from the linked PR how the fix actually fixed the issue, but for what it's worth - I was having the same issue and deleting the `.jekyll-cache` folder fixed it.

From running `jekyll build --verbose` I - well, obviously, started getting these hits

```
           Assets:  Sprockets Cache miss "file_digest:_assets/stylesheets/main.css.sass:1568493544" (3ms)
           Assets:  messaging hooks on before_read through asset
           Assets:  messaging hooks on after_read through asset
           Assets:  Sprockets Cache miss "file_digest:/home/dramalho/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/font-awesome-sass-5.11.2/a" (4ms)
           Assets:   Searched for, and rendered font-awesome/fa-solid-900.eot in 0.0133526s
           Assets:  {:argv1=>"font-awesome/fa-solid-900.eot", :path=>true}
           Assets:   Searched for, and rendered font-awesome/fa-solid-900.eot in 0.001433s
           Assets:  {:argv1=>"font-awesome/fa-solid-900.eot", :path=>true}
           Assets:  Sprockets Cache miss "file_digest:/home/dramalho/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/font-awesome-sass-5.11.2/a" (2ms)
           Assets:   Searched for, and rendered font-awesome/fa-solid-900.woff2 in 0.0092661s
           Assets:  {:argv1=>"font-awesome/fa-solid-900.woff2", :path=>true}
           Assets:  Sprockets Cache miss "file_digest:/home/dramalho/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/font-awesome-sass-5.11.2/a" (3ms)
           Assets:   Searched for, and rendered font-awesome/fa-solid-900.woff in 0.0093648s
           Assets:  {:argv1=>"font-awesome/fa-solid-900.woff", :path=>true}
           Assets:  Sprockets Cache miss "file_digest:/home/dramalho/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/font-awesome-sass-5.11.2/a" (3ms)
```

and the font files were correctly moved to the render folder, whereas before they were missing. Weird stuff

for reference

```
jekyll-assets (3.0.12)
font-awesome-sass (5.11.2)
sprockets (3.7.2) # because 4 explodes
```
