### ISSUE TITLE
jekyll-assets does not create assets folder in Jekyll destination folder

### ISSUE THREAD

**Issue by knice** [jekyll/jekyll-assets#242]
My repository is here: https://github.com/knice/ucsc-ocean-health

- Ruby: `2.2.3`
- Jekyll: `3.1.2`
- mini_magick: `4.4.0`
- ImageMagick: `6.9.3-0 Q16 x86_64 2016-02-10`

Gemfile contains:

````ruby
gem 'autoprefixer-rails'
gem 'bourbon'
gem 'coffee-script'
gem 'jekyll'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'mini_magick'
gem 'neat'
gem 's3_website'
gem 'sass'
gem 'thin'
gem 'uglifier'
````

Contents of `_config.yml`:

````yaml
gems:
  - bourbon
  - neat
  - jekyll-assets

# Structure configuration
source: ./source
destination: ./build

# Site settings
timezone: America/Los_Angeles
title: 'Special Reports from UC Santa Cruz'
description: 'UC Santa Cruz'
permalink: /:title/
url: http://reports.news.ucsc.edu

exclude:
  - _raw
  - .asset-cache
  - vendor
  - .gitignore

markdown: kramdown
kramdown:
  auto_ids: false

# Assets configuration
assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
````

In [this relative include file](https://github.com/knice/ucsc-ocean-health/blob/master/source/west-coast/_features/image-pseudo-electron.html) I have the following code:

```
{% image pseudo-nitzschia-electron.jpg magick:resize:500 alt:'A scanning electron micrograph of Pseudo-nitzschia australis' %}
````

When I run `bundle exec jekyll build`
  - If the `assets` folder does not already exist in the Jekyll destination folder, the build fails with:
````bash
jekyll 3.1.2 | Error:  No such file or directory @ rb_sysopen - /<path-to-my-project-folder>/build/assets/pseudo-nitzschia-electron-d365587a1b45dbe18d35c82848c2f5ee03ebca91be501698bb290a6ecd8562ea.jpg
````
  - If I create an `assets` folder manually, `bundle exec jekyll build` runs successfully.
  - If I remove `magick:resize:500` from the Liquid `image` tag above, `bundle exec jekyll build` runs successfully, even though nearly identical code is in [another relative include file](https://github.com/knice/ucsc-ocean-health/blob/master/source/west-coast/_features/image-pseudo-400x.html) in the same directory:

```` 
{% image pseudo-nitzschia-light.jpg magick:resize:500 alt:'The chain-forming nature of Pseudo-nitzschia' %}
````

I've tried using a different image file, but the error is the same. The `.asset-cache` directory is created successfully in the Jekyll source directory, but the `assets` directory is never created in the Jekyll destination directory. Here is a `--trace` of the failed build:

````bash
/Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/liquid/tag/proxied_asset.rb:72:in `binwrite': No such file or directory @ rb_sysopen - /Users/kalinandrob/Sites/sea-of-mystery/build/assets/pseudo-nitzschia-electron-d365587a1b45dbe18d35c82848c2f5ee03ebca91be501698bb290a6ecd8562ea.jpg (Errno::ENOENT)
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/liquid/tag/proxied_asset.rb:72:in `write_to'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:155:in `block in write_all'
	from /Users/kalinandrob/.rbenv/versions/2.2.3/lib/ruby/2.2.0/set.rb:283:in `each_key'
	from /Users/kalinandrob/.rbenv/versions/2.2.3/lib/ruby/2.2.0/set.rb:283:in `each'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/env.rb:153:in `write_all'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/hooks/jekyll/write.rb:6:in `block in <top (required)>'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/hooks.rb:97:in `call'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/hooks.rb:97:in `block in trigger'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/hooks.rb:96:in `each'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/hooks.rb:96:in `trigger'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/site.rb:204:in `write'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/site.rb:61:in `process'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/command.rb:26:in `process_site'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:33:in `process'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/gems/jekyll-3.1.2/bin/jekyll:13:in `<top (required)>'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/bin/jekyll:23:in `load'
	from /Users/kalinandrob/Sites/sea-of-mystery/vendor/bundle/bin/jekyll:23:in `<main>'

```` 

I can get around this issue by manually creating the `assets` folder in the Jekyll destination folder, but the issue is preventing my Travis-CI builds/deploys from completing successfully.

**Comment by envygeeks** [comment]
What else do you have going on? We do in-fact create your asset folder: https://github.com/jekyll/jekyll-assets/blob/1bef9341e6281a2c87b7c20c07d610c754f6aabd/lib/jekyll/assets/liquid/tag/proxied_asset.rb#L45 when proxying assets and we Sprockets also creates your assets folder.

**Comment by knice** [comment]
I'm using Guard for development, but I don't think that would be an issue.

Everything works fine if I remove `magick:resize:500` from: `{% image pseudo-nitzschia-electron.jpg magick:resize:500 alt:'A scanning electron micrograph of Pseudo-nitzschia australis' %}`

I can even add `magick:resize:500` back in to that include file once the first build has succeeded and everything continues to run fine. This issue only happens when the `assets` folder does not exist and needs to be created in the Jekyll destination folder.

I assume something about the magick proxy is where I should look. Is there any way I can see where the "magick" proxy might be failing?

Here is my `.gitignore` file:

````
.asset-cache
.bundle
.jekyll-assets-cache
.sass-cache
build
vendor
_raw
tmp
````

And the rest of my `Gemfile`:

````ruby
group :development do
  gem 'guard'
  gem 'guard-jekyll-plus'
  gem 'guard-livereload'
end

group :test do
  gem 'rake'
  gem 'scss_lint'
  gem 'html-proofer'
end
````

**Comment by envygeeks** [comment]
I pointed you to exactly where we write proxied assets and create your folder very explictly, we also test that behavior (if I remember right explictly, but) undoubtedly implicitly (as we remove the _site after every test.. which is why our suite is so slow.)

I'll see what I can find and issue a fix is necessary or point you out to where things are going wrong.

**Comment by knice** [comment]
OK, I tracked down the issue. My installed version of jekyll-assets is 2.1.2. In my project folder, in `bundle/gems/jekyll-assets-2.1.2/lib/jekyll/assets/liquid/tag/proxied_asset.rb` the `write_to` function is this:

````ruby
def write_to(name)
  File.binwrite(name, source)
end
````

I realize this isn't an actual bug in jekyll-assets, but do you know why I wouldn't have the latest code (what you linked to in your first response)? I thought the latest version of the gem was 2.1.2.

**Comment by envygeeks** [comment]
@knice if it's not in the latest release that means I caught that bug during one of my normal audits (which is why I probably thought it was in a stable release) and it hasn't been released yet.  I quite often audit my source and fix bugs without thinking twice.  For now you can use master (since you us a Gemfile,) it's pretty much the same with one difference, we do not process all your assets through Liquid (it's going to be optional in 2.2.)

I'll backport that change into a 2.1.3 release tomorrow morning.

**Comment by knice** [comment]
No problem. :+1: I updated my Gemfile to use the master branch and everything works as expected. Thank you for working with me on this (on a weekend too).

**Comment by envygeeks** [comment]
I totally forgot about this and I do apologize, I'll be releasing this in a few minutes.

**Comment by knice** [comment]
No problem on the delay. Master branch worked fine for me. Thanks for releasing the fix!
