### ISSUE TITLE
image_optim in Jekyll 3 Assets

### ISSUE THREAD

**Issue by bndn** [jekyll/jekyll-assets#243]
I found #141 to use image_optim with Jekyll Assets, but I would like optimize images only for the production build. I tried to extend `Hook` and `Sprockets::Compressing` in a Jekyll plugin to use the `"compress" => { "image" => true }` option but I did not succeed.
It would be great if Jekyll Assets could handle image optimization.
Thank you!

**Comment by envygeeks** [comment]
You were probably looking for a proxy on the image assets, I however support this going mainline so I'll handle this and get it done since it *should* be easy since we can probably drop in the Rails plugin, of which we normally readily support.

**Comment by envygeeks** [comment]
Hulk: today.

**Comment by envygeeks** [comment]
Unforuntately this is going to take more work than I though, it's going to have to wait until 2.3 or 3.0, which won't be that long after this release since I've finally completed the big project that was holding back me spending more time with this project.

**Comment by envygeeks** [comment]
This was recently added by a contributor.  Thanks!
