### ISSUE TITLE
Sass files not being processed with --incremental flag when using Jekyll Serve

### ISSUE THREAD

**Issue by BryanSchuetz** [jekyll/jekyll-assets#244]
* Everything works fine and as expected when using `Jekyll serve`. 
* However, when using `Jekyll serve --incremental` changes to .scss files in source, don't cause the .css file in `/assets` to be rebuilt—even though Jekyll sees the change and regenerates
* If I combine my change to .scss files in source with a change to some other page, the .css file in `/assets` is rebuilt with the changes

**Comment by envygeeks** [comment]
This is an upstream issue. Since we do nothing more than tie into the incrementer using it's API there is nothing we can do about it short of notifying @alfredxing and hoping he can debug it upstream. There is an open issue there he plans to look at.
