### ISSUE TITLE
Incrementally builds doesn't work for SCSS / CSS

### ISSUE THREAD

**Issue by obfk** [jekyll/jekyll-assets#245]
### Overview

With the `--incremental` flag, everything appears to be working correctly, with the exception of our `.scss` files. A new build is triggered, but the compiled CSS file remains unchanged. We have however noticed that if you change a `.scss` file, then change a post (`.md`) file, a new build for the CSS _is_ triggered.

Looking through the logs of `jekyll build` we can see that when we save both the `.scss` file and the `.md` file, we correctly generates a cache miss for the said `.scss` file, which then results in correctly rebuilding the respective files. This is exactly the behavior we would also expect when changing a `.scss` file, yet somehow when only the `.scss` file is changed the assets are not rebuilt.

```
Jekyll Assets: Sprockets Cache miss "file_digest:_kb_assets/stylesheets/_articles.scss:1456856958" (1ms)
```

----

**reproduction:**

* change a `.scss` file

**expected:**

* regenerates CSS file

**actual:**

* changes nothing

**interesting:** 

* must modify a `.md` file to trigger rebuild of `.scss`

**reference**

* demo repo: [github.com/obfk/jekyll-assets-test](https://github.com/obfk/jekyll-assets-test)

**Comment by envygeeks** [comment]
We might have an API mixup here, seems like we need to re-integrate with -I flag.

**Comment by envygeeks** [comment]
It looks like we aren't the only addon that might be having this problem.  It was recently reported that several other addons that integrate with incremental regeneration have the same problem.

**Comment by obfk** [comment]
I believe that `--incremental` is currently experimental at the moment, so there could be instability.

**Comment by envygeeks** [comment]
This is an upstream issue.  Since we do nothing more than tie into the incrementer using it's API there is nothing we can do about it short of notifying @alfredxing and hoping he can debug it upstream.  There is an open issue there he plans to look at.
