### ISSUE TITLE
How to pass options to uglifier?

### ISSUE THREAD

**Issue by bjpirt** [jekyll/jekyll-assets#251]
Hello,
Apologies if this is obvious or I've missed something, but I'd like to be able to pass some config to uglifier when it is run so that I can do things like remove comments, etc. Would someone be able to let me know how / if this is possible?
Cheers,
Ben

**Comment by envygeeks** [comment]
At this time there are no plans to allow the configuration of Uglifier as we let Sprockets deal with that as it sees fit.  In the future this could change but at this time there are more important features that will be going out in the next couple of weeks.

**Comment by bjpirt** [comment]
Ah, that’s a shame :-( Guess I’ll need to do my own post-processing since this can’t then
Thanks for the answer.

**Comment by envygeeks** [comment]
Hulk: Today
@bjpirt we will be supporting this, it's useful.

**Comment by bjpirt** [comment]
Much appreciated - thanks!
