### ISSUE TITLE
Support for LESS files

### ISSUE THREAD

**Issue by basex** [jekyll/jekyll-assets#253]
On the documentation it's written:
> sass/less/css files you need do nothing special for the preprocessing an entire file, it's always done.

I have tried to require some LESS files inside a sprockets index file and was not able. I was doing this with the previous version of jekyll-assets that was using jekyll 2.

I suppose the documentation is wrong since sprockets 3 does not have built-in support for LESS. 

Am I correct? 

If I want to add LESS support to this gem, should it be added here ```https://github.com/jekyll/jekyll-assets/tree/master/lib/jekyll/assets/processors``` ?

**Comment by envygeeks** [comment]
You don't need to add anything to our system.  The "nothing special" part is that you don't need to do any work, just add a Gem. Try adding less to your Gemfile and it should work.  Sprockets does support LESS out of the box but you must provide the interpreter.  We do not do not include it on our dependency list by default because it's not Ruby-Native and brings in hefty dependencies we do not carry by default.  Have you tried adding "less" to your Gemfile?

**Comment by basex** [comment]
Yes I have tried to add the LESS gem to ruby and then create a sprockets index file.

Example: file 'style.less' and in a file called 'app.css' I insert:
```
/*
 *= require style 
*/
```
Both in the same folder.

I get the error: ```couldn't find file 'style' with type 'text/css'``` This was previously working in jekyII 2.

If you check this commit in sprockets, you can see that they removed LESS from their documentation: https://github.com/rails/sprockets/commit/8c457c9e0a8220cb42836b51696b7850cb728562

**Comment by envygeeks** [comment]
That seems to be landed in 4.0 not 3.0.  I honestly don't know if you need to do extra work since it was assumed that it should work since we do no altering like Rails.  I'll check it out and see what I can come up with in the next few days.

**Comment by basex** [comment]
I put a small class on my jekyll project to be able to process the LESS files. Works without a problem.

In case anyone needs: https://gist.github.com/basex/c852b296bfe7021072f3

**Comment by envygeeks** [comment]
@basex if you'd like to fit this into how we organize our code and submit a pull (with a test) I'm happy to accept it.

**Comment by envygeeks** [comment]
Hulk: Today.

**Comment by adrienne** [comment]
@envygeeks I don't quite understand how to use LESS with jekyll-assets, still, and it's not documented very well. Is there a writeup anywhere? I'm using the latest version of Jekyll and 2.0.9 of jekyll-assets.
