### ISSUE TITLE
dependencies don't seem to work in .css.liquid

### ISSUE THREAD

**Issue by mroch** [jekyll/jekyll-assets#258]
I'm trying out master (6e8b384), and having some problems with images referenced from .css.liquid files not being generated.

for example,

```
/*= link foo.png */
.foo {
  background: url({% asset_path 'foo.png' });
}
```

does not generate `/assets/foo.png`.

changing to `.scss` and using `url(asset-path('foo.png'))` works.

**Comment by basex** [comment]
Get the code again from master and see if this commit solves your problem https://github.com/jekyll/jekyll-assets/commit/d0643289e42dc575369a511699ca7fce9a7dfeac

**Comment by envygeeks** [comment]
This issue is being closed for lack of response to the given diagnostic attempt.  If you continue to have this problem please comment and we can go from there.

Thanks.
