### ISSUE TITLE
Retina images and FastImage

### ISSUE THREAD

**Issue by sankage** [jekyll/jekyll-assets#260]
For retina images I use the practice of saving my image at 2x size and downsizing their width/height attributes. I noticed that while using the `image` tag it will use FastImage to get the image dimensions and add those attributes automatically, is there a way to instruct it to use those same values / 2 or something?

**Comment by envygeeks** [comment]
At this time there isn't, but I can add it since that's probably something necessary in any asset system.

**Comment by envygeeks** [comment]
Hulk: Today
