### ISSUE TITLE
How would I detect if / what version of jekyll-assets is installed?

### ISSUE THREAD

**Issue by untra** [jekyll/jekyll-assets#262]
If I am writing a plugin for jekyll, I might want to do some different behavior if jekyll-assets is among the listed gems. What would be the best way to detect what version of jekyll-assets is installed?

For example,
```rb
Jekyll::Hooks.register :site, :after_init do |site|
  if site.config['assets']
    # jekyll-assets is installed
  end
end
```
This only detects that `assets` is listed in the site configuration, and feels sloppy. What would the better approach be? Additionally, how would I get the jekyll-assets version?

Thanks!

**Comment by envygeeks** [comment]
You need to get the version the same way you would any gem with Jekyll::Assets::VERSION.  Please ask non-bug related questions at https://talk.jekyllrb.com as this medium is for bugs only, thanks!
