### ISSUE TITLE
Error:  undefined method `partition' for true:TrueClass

### ISSUE THREAD

**Issue by damiencaselli** [jekyll/jekyll-assets#271]
Hello,

I've found that I cannot build Jekyll anymore with any version > `v2.2.3`, and I keep getting this error: `jekyll 3.1.3 | Error:  undefined method `partition' for true:TrueClass`.

This happens just after the last file rendering.

Also, building with the `v2.2.2` works fine, and it seems [lib/jekyll/assets/env.rb](https://github.com/jekyll/jekyll-assets/blob/d15a185031b47f6bf3ea607fe231cba9108d4b4e/lib/jekyll/assets/env.rb#L274-L290) got rewritten in `v2.2.2..v2.2.3`.

**Comment by envygeeks** [comment]
Provide the full error please, a minor context is not relevant, and no, it did not get rewritten, it got adjusted in a few pieces and comments fixed up.

**Comment by damiencaselli** [comment]
Given these 2 builds where the only difference is `jekyll-assets` version, the build [succeeds](https://travis-ci.org/poppy-project/poppy-project.org/builds/127260673) or [fail](https://travis-ci.org/poppy-project/poppy-project.org/builds/127259542).

A couple of gems got updated during this weekend, the codebase was the same.
I tried to build with the exact same gems versions that were working in the [last succeeded build](https://travis-ci.org/poppy-project/poppy-project.org/builds/126646455), and I found changing `jekyll-assets` from `2.2.2` to `2.2.3` was causing this.

**Comment by envygeeks** [comment]
@damiencaselli I found the bug, I'm issuing a hotfix for you right now.

**Comment by envygeeks** [comment]
This issue is fixed with: https://github.com/jekyll/jekyll-assets/commit/cdd367b1aca4a139f0fa3899703225283742dd14.  I was able to successfully build your site.

**Comment by damiencaselli** [comment]
Awesome, thanks! 👍

**Comment by envygeeks** [comment]
Jekyll Asses v2.2.5 has been pushed, you should be able to upgrade now and build.
