### ISSUE TITLE
Bad URI error when using Liquid in SCSS

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-assets#273]
Hi there,

I'm trying to use a Liquid variable in my SCSS file, but I get bad URI error:
```
Liquid Exception: bad URI(is not URI?): {{ page.photo }} in _includes/head.html, included in _layouts/default.html
jekyll 3.1.3 | Error:  bad URI(is not URI?): {{ page.photo }}
```

In my SCSS file I have:
````
background-image: url(asset_path("{{ page.photo }}"));
````

The documentation says that nothing special needs to be done for Liquid pre-processing. I would really appreciate you help.

**Comment by envygeeks** [comment]
Questions like these should be direct to the forums at https://talk.jekyllrb.com.  However, you can read: https://github.com/jekyll/jekyll-assets#liquid-processing-with-your-jekyll-context for more information on our Liquid processing. As stated you'll need to either enable the feature to process all SCSS files as Liquid or make the extension for your SCSS file ".scss.liquid" (which gets liquid processes regardless of whether the feature is enabled.) It's designed this way to prevent clashing on stuff like Handlebars and allow optional processing on stuff you want Liquid explicitly.

**Comment by iloveip** [comment]
Hi @envygeeks,

Thank you very much for your reply. I already have `features.liquid` set to true, but I still get this error. Also if I set it to false and add `.liquid` extension to my `testimonials.scss` file I get the following error:

```
Error in _assets/stylesheets/main.scss:15 File to import not found or unreadable: testimonials.
Load paths:
  /Users/svetlana/Desktop/iloveip/_assets/css
  /Users/svetlana/Desktop/iloveip/_assets/stylesheets
  /Users/svetlana/Desktop/iloveip/_assets/images
  /Users/svetlana/Desktop/iloveip/_assets/img
  /Users/svetlana/Desktop/iloveip/_assets/fonts
  /Users/svetlana/Desktop/iloveip/_assets/javascripts
  /Users/svetlana/Desktop/iloveip/_assets/js 
  Liquid Exception: File to import not found or unreadable: testimonials. Load paths: /Users/svetlana/Desktop/iloveip/_assets/css /Users/svetlana/Desktop/iloveip/_assets/stylesheets /Users/svetlana/Desktop/iloveip/_assets/images /Users/svetlana/Desktop/iloveip/_assets/img /Users/svetlana/Desktop/iloveip/_assets/fonts /Users/svetlana/Desktop/iloveip/_assets/javascripts /Users/svetlana/Desktop/iloveip/_assets/js in _includes/head.html, included in _layouts/default.html
jekyll 3.1.3 | Error:  File to import not found or unreadable: testimonials.

```

**Comment by mryellow** [comment]
> Questions like these should be direct to the forums at https://talk.jekyllrb.com.

First result on google: "You should use google!!!"

@envygeeks Not helpful. DNS error.
