### ISSUE TITLE
CSS File Not Being Replaced When Using Jekyll Serve

### ISSUE THREAD

**Issue by tohuw** [jekyll/jekyll-assets#275]
My config:

    assets:
      cache: false
      autoprefixer:
        browsers: ["last 2 versions","> 5%","IE 9"]

Using jekyll-assets 2.2.5 and Jekyll 3.1.3

Whenever I change any of my Sass files, I see `jekyll serve` (the `JEKYLL_ENV` is `development`) note that a file changed, but `main.css` is never replaced in the output directory. If I manually delete the file and re-run build or serve, it works fine.

What am I missing?

**Comment by envygeeks** [comment]
***Please ask non-bug questions at https://talk.jekyllrb.com/ this medium is for bug reports only. Not generic usage questions or questions on how to use our software.***

---

Check your excludes and make sure something named main isn't excluded, make sure you use the right asset folders (we **do not integrate with jekyll-sass-converter***) and if that doesn't help please post your question to the forums and I'll happily help you from there where we can try to work out what is going wrong with your source.

**Comment by envygeeks** [comment]
If you continue to have problems, please include as much information as you can, including but not limited to your file structure (or preferably a repository with your source in it) so that we can go from there, we cannot work with generic diagnostics because there are many variables that can cause problems.

**Comment by envygeeks** [comment]
Just seen your ticket on our forums and have replied, sorry I did not notice it before: https://talk.jekyllrb.com/t/disable-sass-caching-in-development/2324/4?u=envygeeks

**Comment by envygeeks** [comment]
This was deduced as a browser caching issue, digesting solved the problem.

**Comment by tohuw** [comment]
See my reply in Jekyll Talk. The file isn't changing. I'll try to write some tests when I have time.

**Comment by envygeeks** [comment]
This is a bug, I found out where it originates as I was replying and explaining what we change, a silly bug at that since I should have spotted that when I was adjusting their source to fit our needs.  It's here: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/manifest.rb#L78

**Comment by tohuw** [comment]
Ah, easy to spot now that you've pointed it out! 😄 

At least now I feel slightly less crazy.
