### ISSUE TITLE
Trouble importing .css within .scss file

### ISSUE THREAD

**Issue by tommueller** [jekyll/jekyll-assets#286]
Hi there,

I just installed jekyll-assets and quite like it so far. Handling my js files works like a charm.

I do have a major problem with css import. My folder structure is like this:

```
> _assets
>    -- css
>       -- _sass
>          quite-some-sass-files.scss
>       -- vendor
>          quite-some-css-files.css
>    -- js ...
```

Now for my page I would like to have a `vendor.css` file which contains all the css files from css ->vendor.

The file looks like this right now:

> @import
>   "_sass/_general",
> 
>   // All the third party styles, except the UI framework:
>   "_sass/vendor/plugins/_syntax-highlighting",
>   "_sass/vendor/plugins/_parallax",
>   "vendor/plugins/drawer.min.css"
> ;

which almost works. The scss-files are imported correctly (the oney without file-ending). But the drawer.min.css is only imported as an css  `@import(url/drawer.min.css) `, I would like the content copied to the `vendor.css`.
BUT the real problem is, that I actually don't get the files on the frontend, because `drawer.min.css`
is not linked to the page as an asset itself, so the `@import(url/drawer.min.css) ` actually points to a non existing file.

Any way I can solve this issue?

Thanks a lot
Tom

**Comment by envygeeks** [comment]
Hi @tommueller, while I hate to do all non-bug related questions need to be asked at https://talk.jekyllrb.com where they can help the wider community and where you can be helped by the wider community and maintainers alike.

If you ask your question at https://talk.jekyllrb.com I'll happily try to help you if I can, but for now this issue must be closed because this is a non-issue and stands as a usage (help) question.

**Comment by tommueller** [comment]
Ok sorry, did not now.

Will start a thread at the jekyll-forum. 

Thanks

**Comment by envygeeks** [comment]
Email (Mailgun) is currently down for Jekyll Talk so you might have trouble signing up so I'll go ahead and help you.  What you want are Sprockets requires.  SASS and others do not care about importing anything but their own files.  Sprockets was designed to solve that problem.  This is done the same way as Rails:

```css
//= require ./file.css
Other stuff.
```
