### ISSUE TITLE
Option to add rel="preload" to link tag for async rendering

### ISSUE THREAD

**Issue by nsimonson** [jekyll/jekyll-assets#287]
It would be great if there was a way to get stylesheets in a nonblocking manner. Possibly leveraging loadCSS and/or the new rel="preload" attribute.

**Comment by envygeeks** [comment]
`{% css asset/name.css rel:preload %}` is already supported,

To add it by default or offer an option, I'm not sure if I want to, most people don't know how to optimize what should block and what shouldn't when painting and it will cause more problems than it won't when people start saying "oh async, lets do it!"  This is the very reason Google's website optimizer has a 2 paragraph warning about it.

**Comment by nsimonson** [comment]
That's a great point. rel:preload will work for my needs. Closing this.

**Comment by jhabdas** [comment]
I tested out the `rel:preload` with v2.2.7 and 👌 . Thanks for the hot tip @envygeeks.
