### ISSUE TITLE
Anyway to include jekyll asset_path logic into markdown?

### ISSUE THREAD

**Issue by Sananes** [jekyll/jekyll-assets#288]
Hey guys,

Is there anyway you can include asset_path logic in markdown?

Here's what I mean:

```

---
title:  "Conflux"
layout: work
services: "Web Design, UI/UX"
images:
  - image: '{% asset_path work-sample.jpg %}'
```

**Comment by envygeeks** [comment]
Unfortunately no. This is a limitation by design in Jekyll as it would add
hefty overhead to Liquid parse the front matter. However, I will concede
that I am not fully sure that the overhead is a case as much as it was
previously since now we always carry an open Liquid parser.

**Comment by envygeeks** [comment]
We have no plans to support this feature, as I feel it would be a waste of development time for a feature that is not widely requested.  We do however accept donations for features if you feel this feature is extremely important to you.

**Comment by marcoramires** [comment]
How would you recommend to use assets and `<meta property="og:image" content="{{page.image}}">` together?

**Comment by envygeeks** [comment]
Please don't necromance, and jack threads @marcoramires.  You can pass liquid variables into `{% asset %}` as outlined in the Documentation.

**Comment by marcoramires** [comment]
Ufff... My bad! I missed that completely. 'Necromance' 👍
