### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by tomas-zemres** [jekyll/jekyll-assets#296]
It is complicated identify what is wrong in my source, because raised exception does not reports any details.

For example error: "Liquid Exception: Unknown proxy argument. in about.md"

 there is not clear:
- which proxy argument is not correct? (print the key into the exception message)
- which tag contains error? (print whole tag with all arguments or print line-number in sourcefile, if it is possible)

**Comment by envygeeks** [comment]
This is fixed in 3.x which will be released this upcomming week.
