### ISSUE TITLE
Proxies don't support changing the type of an asset

### ISSUE THREAD

**Issue by spudowiar** [jekyll/jekyll-assets#298]
Proxies don't support changing the type of an asset as `Sprockets.register_transformer` does. As far as I can tell, there are currently two technical reasons we currently don't have this support but they are easy to rectify and **I've nearly completed a patch.**

The first reason is that there is simply no API to do so. Firstly we must establish whether to deal in file extension or mime type. I suggest mime type and `ProxiedAsset#content_type=`.

The second reason is that Jekyll Asset's internal cache does not support changing the extension. This is easily rectified by looking up only the `basename` of the cached filename using `Dir.glob`. This also means, after a proxy has been called, if it used `ProxiedAsset#content_type=`, the old cached file will be deleted. There is no reason to keep this file around since we cache based on a digest of the proxies used and it will only confuse the cache and take up space.

Thoughts?

/cc @envygeeks

**Comment by envygeeks** [comment]
I'm on board but my thoughts are that the cache should only be cleaned on the next write.  Doing it at any other time makes the GIL kick in at a terrible time since most of our stuff should be working in memory and Sprockets is already slow enough.

If you want to ship a patch I'm happy to review it and get it put into master ASAP.

**Comment by spudowiar** [comment]
Thanks for the reply! 

> my thoughts are that the cache should only be cleaned on the next write

But how do I do that? This code I'm using basically stores the previous `content_type` before running a proxy and compares it to the current `content_type` after.

**Comment by spudowiar** [comment]
@envygeeks does Jekyll Assets have a utility module I could stick common utility methods in?
