### ISSUE TITLE
building js file from _data file fails 

### ISSUE THREAD

**Issue by primerano** [jekyll/jekyll-assets#300]
This might be a chicken and egg issue but here it is

I have a js file that is built using a filter that reads a csv file from the _data directory
### foo.js

```

---
layout: null

---
var my_data = {{ 'a-csv-file-from_data' | build_json_from_csv }}

```
### The filter snippet

```
def build_json_from_csv(csv_filename)
      data = @context.registers[:site].data[csv_filename]

```

When this is called from jekyll-assets, @context.registers[:site].data has not been loaded yet and is an empty hash.

I could go crazy and load it myself, but this seems like a bad idea.

```
      if @context.registers[:site].data.keys.empty?
        @context.registers[:site].data = DataReader.new(@context.registers[:site]).read(@context.registers[:site].config["data_dir"])
      end
```

I could also punt on using the automatic loading of files in _data and process the csv myself but I figured I should try to do things the Jekyll way.

Any suggestions?

Thanks!
Tony

**Comment by envygeeks** [comment]
This might be an upstream issue and I don't think there is anything I am willing to do about it because I don't quite understand why it wouldn't be available.  Maybe @jekyll/core can give more insight but AFAIW it should be populated.  We literally pull the renderer from the liquid context we are given from liquid in circular.  So site is the context we pull site's context from through Liquid's site context.  This is given to us from Jekyll through Liquid and passed back to Jekyll through Liquid.

If you can provide an example repository I'll happily look into it this weekend when I have a minute but I make no promises I can fix it and won't push this upstream for them to deal with since this would originate as problem there most of the time (from my assumptions at this point.)

**Comment by parkr** [comment]
@envygeeks I don't know how jekyll-assets is architected but this would be a problem if it rendered liquid before `Site#read` was called, used its own instance of `Jekyll::Site`, or if it didn't propagate the `Jekyll::Site` instance into `context.registers[:site]`.

**Comment by envygeeks** [comment]
@parkr we pull Jekyll's instance on it's own initialize and we process after Jekyll is done processing, I wonder is there more data we need to add to our processor? This is where we pull out the renderer and render: https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/processors/liquid.rb#L18-L22

**Comment by primerano** [comment]
I created an example repository

https://github.com/primerano/jekyll-test/tree/master

**Comment by parkr** [comment]
@envygeeks Ah, yeah, that's the trouble – this should be the `Jekyll::Site` object, but it's a `Jekyll::Drops::UnifiedDrop` instead. See [the core source code](https://github.com/jekyll/jekyll/blob/9278eb8fcec85b17573c6658d7d67ef6ea6ffb92/lib/jekyll/renderer.rb#L55) – it references the `site`, not `site.site_payload`.

**Comment by envygeeks** [comment]
Hmmm... I'll see what I can figure out about getting this fixed sometime this week. Thanks for the headsup.

**Comment by primerano** [comment]
I'm not sure if it breaks anything else but changing the jekyll-assets setup hook to run post_read instead of after_reset ensures the data object is populated.

https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/hooks/jekyll/setup.rb#L7

**Comment by envygeeks** [comment]
@primerano if you submit a pull and the tests pass, I'll accept it as a valid fix until somebody says that something actually breaks, but the test pretty well cover most cases of asset generation (quite literally in some areas.)

**Comment by primerano** [comment]
The tests still work with my change

* https://github.com/primerano/jekyll-assets/commit/bb4ff8ea6f72617fe092ba63b580dd6aabe029c3

but I wanted to add a test and I came up with the following

* https://github.com/primerano/jekyll-assets/commit/5cdfe5d57b56923074fd1bd58db8479a95b1a3ac

It seems to pass even if I revert my fix.  Any idea what I did wrong?

**Comment by envygeeks** [comment]
Fixed in 3.x
