### ISSUE TITLE
Inconsistent building of image assets in SCSS (asset_path)

### ISSUE THREAD

**Issue by dombarnes** [jekyll/jekyll-assets#304]
I've read other issues raised on this and there seems to be no clues on what the issue is so far, so here's my input.

I've added details of my setup on this gist:
https://gist.github.com/dombarnes/a1f8bc2695afb23a9deadfa5b7425bf7

I have tried many combinations of:

```
JEKYLL_ENV=development jekyll build
JEKYLL_ENV=development bundle exec jekyll build
JEKYLL_ENV=production jekyll build
JEKYLL_ENV=production bundle exec jekyll build
jekyll clean && JEKYLL_ENV=development jekyll build
jekyll clean && JEKYLL_ENV=development bundle exec jekyll build
jekyll clean && JEKYLL_ENV=production jekyll build
jekyll clean && JEKYLL_ENV=production bundle exec jekyll build
```

as well as manually deleting the _site folder and running all these, and i can't find any common pattern in when it does and doesn't build my two images indicated from the asset_path url:
- Switching between asset_path and asset_url doesn't help
- Forcing digest on or off doesn't help either.
- Overwriting existing _site folder vs deleting _site folder doesn't help
- Using jekyll clean doesn't make any difference

Sometimes I'll change it to asset_url and they'll appear on a build, then I'll run the build again, and they won't. Then I'll change it back to asset_path, and they don't build. Sometimes they appear in a development build, sometimes in a production build.
Any assets I'm referring to in html files build fine, some jpg, some png. 

Its pretty frustrating as I can't consistently be sure all my assets are going to be there when I deploy.

Other notes:
Ruby 2.3.1 (installed with rbenv (installed with homebrew (installed from bash)))
OSX 10.11.5

My whole site isn't on GitHub, but if it helps i can push it up for verification.

**Comment by envygeeks** [comment]
@dombarnes yes, it would be nice since I don't have the problems that everyone else has with my own site, but that's probably because I've no images on my site.  I know we test SASS with image's inside of the tests in a few spots and those tests haven't failed so I know it's resolving.

I'm happy to spend an hour or so today looking at it.

**Comment by dombarnes** [comment]
Try cloning https://github.com/dombarnes/trilby-test
Just did it myself, from clean
First build - header_image and campaign_image appear in _site/assets/
Run jekyll clean
Second build - doesn't appear

I tried deleting the .asset-cache folder, and that *may* "fix" the issue.

**Comment by envygeeks** [comment]
Hulk: +private +pull-and-report

**Comment by mk84** [comment]
Same here. It only works when I delete the .asset-cache folder everytime or just set cache to false.

**Comment by davidstosik** [comment]
Same here, thanks for the tip about deleting the `.asset-cache` folder, very helpful!

**Comment by tomschlenkhoff** [comment]
Same problem here, wasted a day on trying to track it down. Thanks @mk84 that trick (delete the .asset-cache folder) helps me consistently.

**Comment by envygeeks** [comment]
This issue is resolved in 3.x
