### ISSUE TITLE
jekyll-assets 2.2.7 and susy 2.2.12 not working

### ISSUE THREAD

**Issue by GitHub-Mike** [jekyll/jekyll-assets#305]
I use:
  * jekyll 3.1.6
  * jekyll-assets 2.2.7
  * susy 2.2.12

under:
  * Windows 7 64bit
  * x64-mingw32
  * ruby 2.2

main.scss is in _assets\css and @import "susy" is not working.

```
                  Asset inconsitency, expected
jekyll 3.1.6 | Error:  undefined method `logical_path' for nil:NilClass](url)
```

**Comment by envygeeks** [comment]
I don't know what susy is and we do not currently support it, as for the error, I'll happily fix that, but that doesn't mean that susy will work, or that we plan to support it, if ever.

**Comment by GitHub-Mike** [comment]
[Susy](http://susy.oddbird.net/) is a Sass-based grid framework.
I wanted to use it with jekyll.
Can you explain the error to me at least.
I think the problem is the lack of susy files in assets stylesheet directory.

**Comment by envygeeks** [comment]
The error is caused by us not being able to find the asset yes. If it is
for sass I might support it . Once I'm out of the data centre I'll see
about supporting it and fixing the error for other unfindable assets.

**Comment by GitHub-Mike** [comment]
Susy is working now on a clean Jekyll project.
I do not know exactly where the error was.
Maybe you can make a more specific error message with exception handling.
`Asset inconsitency, expected`
