### ISSUE TITLE
[Exception] Asset inconsitency, expected

### ISSUE THREAD

**Issue by meNESS** [jekyll/jekyll-assets#309]
Hi,

I'm getting following exception. How can I solve that?
**Note:** I'm using the latest version of Jekyll and Assets
> $ jekyll build
> Configuration file: xxx/_config.yml
> DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
> Please register a mime type using `register_mime_type` then
> use `register_compressor` or `register_transformer`.
> https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
>  (called from block in <top (required)> at C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
> DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
> Please register a mime type using `register_mime_type` then
> use `register_compressor` or `register_transformer`.
> https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
>  (called from block in <top (required)> at C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
> DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
> Please register a mime type using `register_mime_type` then
> use `register_compressor` or `register_transformer`.
> https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
>  (called from block in <top (required)> at C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
> DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
> Please register a mime type using `register_mime_type` then
> use `register_compressor` or `register_transformer`.
> https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
>  (called from block in <top (required)> at C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.2.7/lib/jekyll/assets/processors/liquid.rb:35)
>             Source: xxx
>        Destination: xxx/_site
>  Incremental build: disabled. Enable with --incremental
>       Generating...
>                     Asset inconsitency, expected
> jekyll 3.1.6 | Error:  undefined method `logical_path' for nil:NilClass

**Comment by meNESS** [comment]
`jekyll clean` command fixed the issue.

**Comment by bachirelkhoury** [comment]
I'm getting this error as well. Jekyll clean didn't help.

**Comment by meNESS** [comment]
@bachirelkhoury Run `jekyll clean` command, then delete `.assets-cache` and `_site` directories. Now run `jekyll build` command.

**Comment by mattfelten** [comment]
I'm getting the same error. `jekyll clean` + others is doing nothing for me.

**Comment by envygeeks** [comment]
We do not integrate with Jekyll Clean because it provides us no API to do so.  You need to manually delete .asset-cache and built from fresh.

**Comment by mattfelten** [comment]
Sorry. My issue is all the depreciation warnings. Not the `Asset inconsistency, expected` which I didn't notice.

Opened https://github.com/jekyll/jekyll-assets/issues/313

**Comment by envygeeks** [comment]
@mattfelten this issue is already addressed on master and a release will happen tomorrow.
