### ISSUE TITLE
Assets from gem based theme

### ISSUE THREAD

**Issue by SirRawlins** [jekyll/jekyll-assets#310]
Followup to the JekyllTalk discussion we were having about assets in gem based themes (https://talk.jekyllrb.com/t/jekyll-assets-gem-based-theme/2667/2). I've worked up an example theme and consuming site to illustrate what is happening.

Example Site: https://github.com/SirRawlins/jekyll-theme-site
Example Theme: https://github.com/SirRawlins/jekyll-theme

When trying to build the site the plugin outputs a debug of the `asset_config["sources"]` which seems to suggest the path for the assets is correctly added, however it's still unable to find the files throwing the error `Liquid Exception: Could not find the asset site.css in _layouts/default.html`

I've tried this using system level installs of the theme, and also used `bundle package` so that the theme files sit within the site on the FS but both yield the same result.

Any thoughts?

**Comment by SirRawlins** [comment]
Spent some time looking at this, and it seemed that despite the plugin adding the themes asset paths to the config this wasn't then being pushed through to Sprokets.

I've just modified the plugin to call Sprokets `append_path` directly and it appears to now find the asset, and also has the benefit of not requiring that the theme be bundled under the site root.

https://github.com/SirRawlins/jekyll-theme-site/blob/2acfb0b7d1a8ac8c4709439a714ec6c53167055f/_plugins/jekyll-assets-theme.rb

I have a hunch that this approach isn't going to be sustainable though as the fact we're bypassing the jekyll-assets config means the asset will be lost for other uses? Also less-deal from a security point of view?

**Comment by envygeeks** [comment]
You aren't overriding anything.  You are literally appending the paths as was designed, you are using the outer API's as they are intended to be used and exactly how I want them to be used.  You are on the right path!

**Comment by SirRawlins** [comment]
@envygeeks thanks for the vote of support. I'll continue down this path and see where it takes me.

**Comment by envygeeks** [comment]
https://github.com/jekyll/jekyll-assets/wiki/Jekyll-%22Gem-Themes%22-and-Paths
