### ISSUE TITLE
Unable to find how to configure autoprefixer-rails

### ISSUE THREAD

**Issue by nhoizey** [jekyll/jekyll-assets#314]
As suggested in Jekyll Assets documentation, I installed [the `autoprefixer-rails` gem](https://github.com/ai/autoprefixer-rails), and my CSS is indeed modified by Autoprefixer with a few vendor prefixes added to it.

But I can't find how to configure which browsers I want to support.

I've tried several file names:
- `_autoprefixer.yml`
- `autoprefixer.yml`
- `browserslist`

Any hint?

**Comment by DirtyF** [comment]
@nhoizey apparently it's config/autoprefixer.yml: https://github.com/ai/autoprefixer-rails/blob/75fb05f5ac5338acb143b52e4b61a171cddf1796/lib/autoprefixer-rails/railtie.rb#L25

**Comment by nhoizey** [comment]
@DirtyF the README says this:

> If you need to specify browsers for your Rails project, you can save them to
> - `browserslist` and place it under `app/assets/stylesheets/` or any of its ancestor directories
>    ```
>    > 1%
>    last 2 versions
>    IE > 8 # comment
>    ```
>
> - Or `config/autoprefixer.yml`
>    ```
>    flexbox: no-2009
>    browsers:
>    - "> 1%"
>    - "last 2 versions"
>    - "IE > 8"
>    ```

So I though placing a `browserslist` file at the root of my Jekyll site would be OK, but it doesn't seem to be.

And @ai answered this:
https://github.com/ai/autoprefixer-rails/issues/100#issuecomment-237636603

So, `browserslist` should be possible:
https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/processor.rb#L92-L102

I'll try with `config/autoprefixer.yml`

**Comment by nhoizey** [comment]
`config/autoprefixer.yml` doesn't seem to do anything… 😢

**Comment by envygeeks** [comment]
We do not support autoprefixer.yml and have no plans to, we only support configuring it through Jekyll Assets configuration.  You are looking for:

```yml
assets:
   autoprefixer:
     theirjunk: configuration
```

**Comment by nhoizey** [comment]
@envygeeks THANKS A LOT!

I had to imagine several configurations that I could put instead of this nice and engaging `theirjunk`, and I think I came up with the right syntax:

```yaml
assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
```
