### ISSUE TITLE
Pulling values out of the assets array with dynamic include params

### ISSUE THREAD

**Issue by nickjj** [jekyll/jekyll-assets#317]
In the documentation it says you can do this `{{ assets["images.jpg"].width  }} => 62` and this works, but how would you handle a situation where "images.jpg" is a variable supplied by an include argument?

---

Example usage:

`{% include gallery.html gallery=foo image=hello.jpg`

Example directory structure:

`_assets/images/galleries/foo/hello.jpg`

**Example working** gallery.html with hard coded values:

`{{ assets["galleries/foo/hello.jpg"].logical_path }}`

**Example not working** gallery.html with dynamic values:

`{{ assets["galleries/{{include.gallery}}/{{include.image}}"].logical_path }}`

---

Is what I'm doing even possible, if so what's the syntax?

If it's not possible, is there any way to access the `{% image %}` tag from within a custom plugin?

**Comment by nickjj** [comment]
Working solution:

```
{% capture foo %}galleries/{{ include.gallery }}/{{ include.image }}{% endcapture %}
{{ assets[foo].logical_path }}
```

**Comment by envygeeks** [comment]
@nickjj that is really the only solution as past the point of us creating the drops it's really up to Liquid.  I don't know that we can create an easier way than the solution you came up with.
