### ISSUE TITLE
Can't add font from assets directory to SCSS

### ISSUE THREAD

**Issue by LisaBee224** [jekyll/jekyll-assets#321]
I exported a custom font from Icomoon, downloaded it, and added the directory to my assets folder. 

In my config file, I added:

```
assets:
   sources:
     -_assets/fonts
```

In my SCSS file, I have:

```
@mixin embed-font($icomoon){
    @icomoon{
    font-family: $icomoon;
    src: url(asset_path($../assets/fonts/fonts/icomoon+".ttf") format('truetype')
}
};
```

But I keep getting the error message : "Invalid CSS after "...url(asset_path(": expected ")" was "$../assets/font..."

I'm new to Jekyll and really not sure how to do this. Can anyone please help?

**Comment by RishikeshDarandale** [comment]
Can you please try below?
```
@mixin embed-font($icomoon){
    @icomoon{
    font-family: $icomoon;
    src: url(font_path('fonts/icomoon.ttf"') format('truetype')
}
};
```

Assumption is that you have folder structure as ```_assets/fonts/fonts/icomoon.ttf```.

**Comment by envygeeks** [comment]
What @RishikeshDarandale said is correct.  You should use strings.
