### ISSUE TITLE
Sources Directives Not Being Honored in Config

### ISSUE THREAD

**Issue by tohuw** [jekyll/jekyll-assets#322]
The fonts are never copied to the new location.

[My jekyll-assets Config](https://github.com/tohuw/tohuwnet-sources/blob/7b449195574c6c14a43f2bc7edb4803b06aa07d8/_config.yml#L121-L130)

[My Assets Folder](https://github.com/tohuw/tohuwnet-sources/tree/7b449195574c6c14a43f2bc7edb4803b06aa07d8/_assets)

[The resulting site's assets folder](https://github.com/tohuw/tohuw.github.io/tree/a0b3a78da8f92958e3345dabfaba9d3297a576dc/assets)

Why isn't this working?

**Comment by envygeeks** [comment]
Hey @tohuw, unless your SASS (probably inside of the `_fonts.scss` file) use the fonts directly via the helper `asset_path` (or `font_path`) or you tell us to always compile the assets (as per: https://github.com/jekyll/jekyll-assets#configuration `assets.assets` with a value of `*.ttf`, `*.woff2`) we won't compile the asset for you.  We make no assumption that an available asset is a wanted asset on the final site (as you can do many things with those assets.) This is a feature to help you minimize the resources your site consumes upon compile (an optimization if you were to press me on the matter.)
