### ISSUE TITLE
jekyll 3.0.1 | Error:  undefined method `map!' for nil:NilCla

### ISSUE THREAD

**Issue by alipseight** [jekyll/jekyll-assets#323]
When i put this command
`bundle exec jekyll serve --config ./_config-dev.yml
`
The terminal, returns:

`Configuration file: ./_config-dev.yml
jekyll 3.0.1 | Error:  undefined method `map!' for nil:NilClass`

What i do ?

**Comment by envygeeks** [comment]
Please file this bug upstream @alipseight at https://github.com/jekyll/jekyll/issues/new as that would be an upstream issue unless it originates from Jekyll::Assets.  Thanks!
