### ISSUE TITLE
Liquid Warning: Liquid syntax error: Expected end_of_string but found id in

### ISSUE THREAD

**Issue by ShintaroNippon** [jekyll/jekyll-assets#324]
i'm using this line of code

`<img data-animate="zoomIn" srcset="{{ 'device1.png' | asset_path | magick:resize:549x395 magick:quality:100 }} 1024w, {{ 'device1.png' | asset_path | magick:resize:280x201magick:quality:100 }} 640w" src="{{ 'device1.png' | asset_path | magick:resize:549x395 magick:quality:100 }}" alt="Mac" style="width: 100%; top: 0; left: 0;">`

but i'm getting a liquid error like this

> 
Liquid Warning: Liquid syntax error: Expected end_of_string but found id in "{{ 'device1.png' | asset_path | magick:resize:549x395 magick:quality

Can you help me with the right syntax of this ?

Thanks in advance. Carlos Vieira

**Comment by DirtyF** [comment]
Please note that this repository's issues are dedicated to Jekyll's bugs. You can ask any question related to Jekyll's usage on [https://talk.jekyllrb.com/](https://talk.jekyllrb.com/). 

Thanks.

**Comment by envygeeks** [comment]
The only problem I see with that syntax is a missing space between "magick" on the 280 size.  I would think that's entirely valid Liquid, perhaps somebody on @jekyll/core or Liquid's team (@fw42) can give some insight because I see no problem.

**Comment by ShintaroNippon** [comment]
Thanks by your answer i already make a question on @jekyll talk...
The space is not the problem i believe i already update it...

https://talk.jekyllrb.com/t/liquid-warning-liquid-syntax-error-expected-end-of-string-but-found-id-in/2854/5

Thanks
Carlos Vieira

**Comment by parkr** [comment]
Is `magick` a filter? I see a missing `|` in the last one...

**Comment by envygeeks** [comment]
Actually yeah that's right and a good catch, that should be:

```liquid
{{ "device1.png magick:resize:549x395 magick:quality:100" | asset_path }}
```

Since @parkr pointed out the problem and I provided the solution, this is not a bug, but rather a misuage of the filters syntax, this is not a bug.

**Comment by ShintaroNippon** [comment]
Thanks by your anwser... the warning disappear howver with this line of code
`
        <img data-animate="zoomIn" srcset='{{ "device1.png magick:resize:549x395 magick:quality:100" | asset_path }} 1024w, {{ "device1.png magick:resize:280x201 magick:quality:100" | asset_path }} 640w' src='{{ "device1.png magick:resize:549x395 magick:quality:100" | asset_path }}' alt="Mac" style="width: 100%; top: 0; left: 0;">`

i'm getting another error

> Liquid Exception: Unknown proxy argument. in index.html
09:50:56 web.1   | jekyll 3.2.1 | Error:  Unknown proxy argument.
