### ISSUE TITLE
Using Compass with jekyll assets

### ISSUE THREAD

**Issue by javierburongarcia** [jekyll/jekyll-assets#326]
Hi, I'm trying to enable compass as it is says on the website:

> Compass - add "compass-core" to your Gemfile and "@import 'compass'"

But I'm getting this error everytime, is there anything obvious that I might be missing? Many thanks!

Error in _assets/css/fablabtheme.scss:2 File to import not found or unreadable: compass.

jekyll 3.2.1 and latest jekyll-assets on my Gemfile

**Comment by envygeeks** [comment]
Compass is no longer maintained and we removed support for it a very long time ago (shortly after it was introduced as a matter of fact.) Unfortunately you'll need to add your Compass path manually (or build a plugin) to get unsupported support for Compass as we've no plans to include support for something that is not maintained.

Sorry.

**Comment by javierburongarcia** [comment]
Thanks for the reply, I wasn’t aware of Compass being no longer maintained but after doing some research it might be the time to move on. Best

ps jekyll-assets looks great by the way, I was using a grunt based solution for deployment and I will definitely will use this!
 
@javiburon <http://www.cardcloud.com/javiburon> | @colaborativaeu <https://twitter.com/colaborativaeu/>, agencia de diseño, tecnología y acción social
