### ISSUE TITLE
SHA384 integrity support broken when assets are compressed

### ISSUE THREAD

**Issue by saki7** [jekyll/jekyll-assets#328]
This once seems to be fixed in #282, but unfortunately it seems not working when the configuration option `assets.compress` is set to `true`.

In the commit 1d5c465 I'm wondering `@asset.to_s` should be something like `@asset_precompiled.to_s`

**Comment by saki7** [comment]
pinging @envygeeks

**Comment by envygeeks** [comment]
@saki7 where would we get `@asset_precompiled` from?  Right now we pass the entire Sprockets::Asset instance into that digester, if there is a better way I am game for fixing it!

**Comment by saki7** [comment]
Sorry but I'm afraid I have no idea for that since it's deeply related to the core.

I'm guessing that
1. jekyll-assets fetches the asset content
2. jekyll-assets computes the integrity digest (<- We are at here)
3. jekyll-assets passes the asset content to the compressor
4. Rendering process occurs

So I think we might have to do the step 3 before step 2 and fetch the actual compressed content. Am I correct? If so, there should be a way to achieve it...

**Comment by ckreon** [comment]
I submitted the original SHA256 problems as a bug to the Mozilla team a while back. It is fixed and scheduled to be pushed with release 52, which should be available March 7th. You can verify the fix right now with either the nightly or developer build.

**Comment by saki7** [comment]
@ckreon Please read the title and description.

- This is related to SHA-384, which is a truncated version of SHA-512, and not related to SHA-256. I can hardly believe that the common part of SHA-256 and SHA-512 was broken in Firefox until 2016.
- This issue is not browser specific.
- This issue only occurs when assets are compressed. So, it's not related to the implementation of the hash function at all.

**Comment by ckreon** [comment]
@saki7 Apologies, I thought this was a work-around being used because of the Firefox bug.

**Comment by envygeeks** [comment]
We now directly use Sprockets asset integrity which has improved, this should be resolved in 3.x which is being released this week sometime.
