### ISSUE TITLE
Using asset path with variables

### ISSUE THREAD

**Issue by Pitu-pl** [jekyll/jekyll-assets#335]
Hello

My code
`{% for item in site.players[lang] %}
            <div class="player">
                <div class="player-inside">
                    {% assign path = players/{{lang}}/player-{{forloop.index + 1 }}.jpg %}
                    {% capture image %}{% asset_path path %}{% endcapture %}
                    <img src="{{ image }}" alt="">
                    <p>{{ item.name }}</p>
                    <ul class="socials">
                        {% for social in item.socials %}
                            <li><a href="{{ social[1] }}" target="_blank"><span class="icon icon-{{ social[0] }}"></span></a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}`

Ofc I have error with `{% asset_path path %}`

> Liquid syntax error (line 1): Variable '{{' was not properly terminated with regexp: /\}\}/

It is possible to generate a string and pass it to the asset path?

**Comment by nickswalker** [comment]
Were you able to work around this?
