### ISSUE TITLE
Jekyll's cache not updating CSS

### ISSUE THREAD

**Issue by YuriBrunetto** [jekyll/jekyll-assets#336]
hello guys, here's my problem:
when I run `bundle exec jekyll serve` and update the css while running, I always have to "force reload" my page, pressing Cmd+R a bunch of times.. I have read a lot of issues but none of them fits in my problem. does anyone know what I'm doing wrong? btw, I'm using .scss 

here's my repo: https://github.com/YuriBrunetto/ybrntt/tree/blog?files=1

thanks in advance!

**Comment by piinthecloud** [comment]
Have you taken a look at this:
http://stackoverflow.com/questions/33844817/css-not-loading-correctly-on-jekyll-github

It's possible your config.yml is looking at your remote url, and not your localhost

**Comment by YuriBrunetto** [comment]
I've already fixed my problem. But thanks for answering! 😄

**Comment by newterminator** [comment]
@YuriBrunetto How did you fix your problem. I am having the same issue...
