### ISSUE TITLE
Inconsistent environment logic

### ISSUE THREAD

**Issue by vegardx** [jekyll/jekyll-assets#341]
Hi,

Is there a good reason that the default `JEKYLL_ENV` is set to `production` if unspecified or, and here is the kicker, any other environment except for `development`. 

Unless `production` is specified it seems more natural to fall back on development. A workaround for people who don't use `JEKYLL_ENV` could be providing a boolean switch, that also should default to `false`.

**Comment by envygeeks** [comment]
We require JEKYLL_ENV which is a default part of Jekyll, that will not change, sorry. I see no reason not to enforce JEKYLL_ENV when it's a regular part of most systems, you have NODE_ENV, RAILS_ENV, JEKYLL_ENV and others to define your environment.

As for being ***consistent*** and enforcing production if you do not meet our criteria, it might seem more natural to you to default to development, but it's not natural to me, my users expect certain things to happen by default unless they wish them not to happen by default.

**Comment by vegardx** [comment]
But I can set JEKYLL_ENV=foo (which can exist or not exist, doesn't really matter) and the module will assume that means `production`. This have unintended consequences when you do have more environments than just `production` and `development`, when using things like CI and environments based on branch names, etc. 

In the current state the module assumes that every environment, except `development` actually means `production`.

**Comment by envygeeks** [comment]
I assume I could, I see no problem with that.

**Comment by vegardx** [comment]
Cool, much appreciated! :)

**Comment by envygeeks** [comment]
We default to development now.  We have no plans to add custom environments, you are stuck with either development or production.  However since there was talk against production by default we now default to development.
