### ISSUE TITLE
Images in _assets that aren't referenced by tags aren't moved

### ISSUE THREAD

**Issue by benjaminmikiten** [jekyll/jekyll-assets#343]
I've got a number of images I don't ever reference with any of the helpers to generate tags or paths, because I'm just referencing and including them with javascript later. 

Is it possible to trigger jekyll-assets to move those files over to my built site even though I don't reference them anywhere?

Alternately, I'd like to know if there's a way I can get those path helpers working within my JS, but that's another issue I'll open if that's itself not the solution for this.

**Comment by envygeeks** [comment]
See the assets option in: https://github.com/jekyll/jekyll-assets#configuration as for the latter, right now it's not possible and I don't know that it's worth it to file a ticket as I don't think the effort is worth it to maintain (considering we allow many JavaScripts) we would have to add methods to t he context.  Your best bet for the latter is: https://github.com/jekyll/jekyll-assets#liquid-processing-with-your-jekyll-context

**Comment by benjaminmikiten** [comment]
Thanks for the quick response!
