### ISSUE TITLE
Improving asset pipeline speed

### ISSUE THREAD

**Issue by nickjj** [jekyll/jekyll-assets#346]
Before I start looking at source code, I wanted to see how much work has been done previously to improve build times when working with a lot of assets, especially semi-large images.

This plugin is awesome and with about 20 or so small images, SASS bootstrap, etc., it does everything you would expect in about 3 seconds on my machine (i5 3.2ghz with an SSD) which makes me happy.

However, my blog has around 400x 1mb images and processing them makes my build time go from 3 seconds to ~10-12 seconds. That is 12 seconds in development mode with `--incremental` before I can see any changes.

It's gotten disruptive enough where I'm considering profiling everything and seeing if things can be improved upon, but that's a lot work so I figured I'd ask here to see how much work has been done previously.

Is there a lot of room for improvement or are things pretty tight?

**Comment by envygeeks** [comment]
There is room for improvement (and this source does undergo periodic refactorings) but I think most of the work would need to be done upstream inside of Sprockets. As far as supporting incremental at one time we did (and I don't remember if I removed the source) but I don't quite remember if that feature is even still on the table and headed towards stable.

**Comment by envygeeks** [comment]
Our pipeline is now significantly faster in 3.x because we've not only improved our own source but because Sprockets went through great lengths in 4.x to make the manifest suck less, even our tests now run at 2x speed compared to before.

**Comment by nickjj** [comment]
How far off is 3.0 from being released?

**Comment by envygeeks** [comment]
If I don't get it out this weekend (doubtful, since I'm hydroseeding -- but it's possible since I'm just finishing up a last few bits) it'll be Tuesday or sometime this week, since I won't be here Monday probably.
