### ISSUE TITLE
Assets screws with my data object

### ISSUE THREAD

**Issue by dominikwilkowski** [jekyll/jekyll-assets#352]
Hi there,

I've used the assets pipeline in my project and noticed that the `where` filter fails on keys that have spaces. I initially thought this is a jekyll core bug and created an issue there: https://github.com/jekyll/jekyll/issues/5586.

Drilling into the bug further I found that the issue only occurs with `jekyll-assets` is enabled.
See test here: https://github.com/dominikwilkowski/jekyll-test

Hope this helps to find the bug.

**Comment by envygeeks** [comment]
I'm intrigued because we don't go anywhere near Jekyll's filters.

**Comment by sheck** [comment]
I noticed this while use jekyll-assets and just assumed it was a limitation of jekyll. Here is a sample of what I used to work around it:

```
{% capture whereExpression %}person.title == '{{ include.name }}'{% endcapture %}
{% assign _person = site.people | where_exp: "person", whereExpression | first %}
```

**Comment by sheck** [comment]
Related to #340

**Comment by envygeeks** [comment]
Yeah that says the same thing I implied to you, I'll be carving out some time to look into all of the Jekyll-Assets and Jekyll-Docker stuff as much as I can because it's been a while since I've looked at any of it.

**Comment by pathawks** [comment]
According to `git-bisect`, this was introduced with eafd2d28c9ff2120c19d3c8579a1b63e91edea74

That lead me to the **extras** :gem: where I found [the source of the problem.](https://github.com/envygeeks/extras/blob/d5da6d59e63c002c48a164384687270be8252587/lib/extras/string.rb#L25-L30)

**Comment by envygeeks** [comment]
I'll make sure it's fixed this weekend in both libraries.

**Comment by abeMedia** [comment]
Any update on this? I'm still encountering this error.

**Comment by envygeeks** [comment]
This is fixed upstream in extras tonight and will be released today or tomorrow morning.
