### ISSUE TITLE
Jekyll Assets & Gem-Based Jekyll Themes

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-assets#353]
This ticket is regarding the same stuff I pointed out in Jekyll earler in the day.. re-opening it here for consolidation of all my observations regarding this..

@envygeeks, you don't have to reply to this ticket because you have already stated your stance repeatedly..  
you may simply apply fixes silently or ignore this entirely (because it may be really Jekyll's fault like you say..)

So what I'm saying throughout this ticket is.. 
--- " **I'm not able to override theme-gem code when I use `jekyll-assets v2.2.8`** " ---

**Comment by ashmaroli** [comment]
## Jekyll Site Tests (uses Jekyll v3.2+)
### With Jekyll 3.2.1
- `jekyll new testblog`
- modify `Gemfile` to use Jekyll 3.2.1, Minima 1.2, JekyllAssets 2.2.8
- copy-paste `_includes/head.html` from Minima gem to `source_dir`
- modify **`<source>/_includes/head.html`** by **deleting** the line that calls for `main.css`
- `bundle exec jekyll serve`
- Point browser to `http://localhost:4000`

=> I **expect** to see an **un-styled** blog.. but I get a fully styled blog instead..

### With Jekyll 3.3.0 / Jekyll 3.3.1
- Repeat the steps above but with ( Jekyll 3.3.0 / Jekyll 3.3.1 ) & Minima 2.1.0
=> Same expectation and same result

**Comment by ashmaroli** [comment]
I first reported it in [this comment](https://github.com/jekyll/jekyll-assets/issues/331#issue-175917348)
An issue-ticket was opened in response to it.. but was closed based on [Parker's comment](https://github.com/jekyll/jekyll/issues/5343#issuecomment-246042344) **and** [my misunderstanding of the issue](https://github.com/jekyll/jekyll/issues/5343#issuecomment-246082925)

**Comment by ashmaroli** [comment]
jekyll/jekyll#5639 occurs because of this same *bug*
When this plugin is loaded, Jekyll no longer detects `<source>/_includes/` (or any other scaffold-directory for that matter..)

**Comment by envygeeks** [comment]
I do plan on testing it and figure out where it resides for sure and fixing it no matter where it resides, my stance on it being an upstream bug doesn't change that any, the odd part is how little we mess about with Jekyll and how we are causing it.  I'm more intrigued as to how we are causing it then who's fault it is really.  I wanna know how.

Again, my stance on who's fault it is doesn't mean I wo't be looking into it.
