### ISSUE TITLE
CSS not full recompiled after JEKYLL theme update via bundle

### ISSUE THREAD

**Issue by git-no** [jekyll/jekyll-assets#354]
## Situation
After a version update of Jekyll-Theme via ```bundle update``` the new theme version is listed in Gemfile.lock.
But ```jekyll s```or ```jekyll b```do not create a new css including the changes of the new theme css.

_assets/main.scss links to the theme SCSS and does compile the SCSS into css, but just the old version.

Workaround: only when _/assets/main.scss content has changed, Jekyll Assets fetches and recompiles the theme SCSS.

Jekyll: v3.3.1
Jekyll-Assets: v2.2.8

## Expected
New css is created including the latest css/scss of the theme for every Jekyll build when Theme version in bundler has changed, better theme code has changed.

**Comment by envygeeks** [comment]
This should be fixed in 3.x, which will be released this upcomming week.
