### ISSUE TITLE
Add option to inline CSS

### ISSUE THREAD

**Issue by opieters** [jekyll/jekyll-assets#356]
Critical CSS should be inline to increase rendering speed. 

https://developers.google.com/speed/docs/insights/InlineCSS

**Comment by envygeeks** [comment]
This is not a Jekyll-Assets bug.

**Comment by opieters** [comment]
@envygeeks No. It's more like a feature request. Since this is more and more becoming important if one wants a good page ranking.

**Comment by envygeeks** [comment]
Fair enough, thanks for the elaboration.  I'm going to re-open and consider but tbh, I think this might be out of our scope or at least something we won't be looking at doing for a while.

**Comment by publicarray** [comment]
you do this with
```html
<style>{% asset inline.scss %}</style>
```

**Comment by opieters** [comment]
That seems an option. However, it's not possible to have a matching [(subresource) integrity-hash](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) that way. This possibility for a hash value is why I switched to this assets pipeline, so it's a bit silly to leave it out then...

**Comment by publicarray** [comment]
Yes it's a bummer and I think it's great that you want to use SRI. 

SRI is useful when the resource is on a CDN or on a seperate host and you want to make sure that the resources is the one you intended. Now if you have have your html and resources on the same host (e.g they are both processed through jekyll or other pipline and I assume they are hosted together) than a SRI is useless; because if an attacker managed to change the resource, what stops them from modifying the hash also?

I'm not trying to attack you. I just wanted to make the limitations of SRI clear.

From the link you posted:
> Subresource Integrity (SRI) is a security feature that enables browsers to verify that files they fetch (for example, from a CDN) are delivered without unexpected manipulation. It works by allowing you to provide a cryptographic hash that a fetched file must match.

**Comment by envygeeks** [comment]
Yeah SRI isn't really meant for (and I don't even think browsers care about) inline CSS an stuff.

**Comment by opieters** [comment]
Ok. You can close the issue then.
However, newer browsers do care about a correct hash value if the headers have certain options.

**Comment by publicarray** [comment]
> headers have certain options

Are you talking about the Content Security Policy ?

**Comment by opieters** [comment]
I mean that the Content Security Policy header is added by the server. This header contains the SRI settings.

**Comment by envygeeks** [comment]
It looks like you can whitelist the SHA hash we provide, so I'll add support for this.

**Comment by publicarray** [comment]
Just in-case this is of use:
An example of a hash in the CSP (not to be confused with the [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#Examples))
```
Content-Security-Policy: script-src 'sha256-076c8f1ca6979ef156b510a121b69b6265011597557ca2971db5ad5a2743545f'
```
```html
<script>var inline = 1;</script>
```
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

> \<hash-source\>
> A sha256, sha384 or sha512 of inline scripts or styles. When generating the hash, don't include the <script> or <style> tags and note that capitalization and whitespace matter, including leading or trailing whitespace. See unsafe inline script for an example.

**Comment by envygeeks** [comment]
We won't directly support outputting the HTML but in Sprockets 3.x you can do `{% css bundle.css @source %}` and it will return the source, you can do it with any asset, regardless of type.  And if it's an image you should also be able to do `{% img name.png @data %}` and get back a data uri.

**Comment by alvarotrigo** [comment]
> you can do this with `<style>{% asset inline.scss %}</style>`

@publicarray  I can't. I get the following message:

> Liquid Exception: Liquid syntax error (/Library/WebServer/Documents/blog/_includes/head.html line 35): Unknown tag 'asset' included in /_layouts/default.html

**Comment by publicarray** [comment]
@alvarotrigo In the new version it's `<style>{% asset inline.scss @inline %}</style>`
