### ISSUE TITLE
Fatal errors in version 2

### ISSUE THREAD

**Issue by slfc** [jekyll/jekyll-assets#357]
Hello,

When I use the latest version of Jekyll-assets, I keep getting the following errors:

### Includes error
```
  Liquid Exception: Could not locate the included file 'call-to-action.html' in
any of ["C:/Users/Lizzy/My", "Documents/websites/tofa/source/_jekyll/_includes"]
. Ensure it exists in one of those directories and, if it is a symlink, does not
 point outside your site source. in /_jekyll/_layouts/post-beauty.liquid
jekyll 3.3.1 | Error:  Could not locate the included file 'call-to-action.html'
in any of ["C:/Users/Lizzy/My", "Documents/websites/tofa/source/_jekyll/_include
s"]. Ensure it exists in one of those directories and, if it is a symlink, does
not point outside your site source.
```
This error gets thrown for every included file. It seems includes are no longer recognized. 

### `@import` error
When I remove all includes, I get the following error:
```
jekyll 3.2.1 | Error:  File to import not found or unreadable: _variables.
Load paths:
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/css
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/stylesheets
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/images
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/img
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/fonts
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/javascripts
  C:/Users/Lizzy/My Documents/websites/tofa/source/_assets/js
```

Anything I `@import` in .scss files is not recognized. I tried everything, including renaming files, moving them around in directories etc. Only after I removed `@import` lines in .scss, it would compile.

Something to note about this problem is that `@import` a package from a gem, like `bootstrap-sass`, would work without problems.

The fact that it wasn't working was making me so frustrated I wanted to give up on using Jekyll-assets, until I realized the problem may lie in the version. I downgraded to version 1.0.0 and it works perfectly. I'm wondering what is causing the problem. 

I tested all versions and found out the `@import` error gets thrown starting from version 2.0.0 and the includes error starting from version 2.1.0.

**Comment by drewish** [comment]
I'm also running into this error. It's frustrating that there's no change log in the repo to help see what'd changed between versions.

**Comment by envygeeks** [comment]
@drewish use the git log, that's why it exists.

**Comment by envygeeks** [comment]
On a side-note this is an upstream problem, that will be fixed in another library.

**Comment by drewish** [comment]
Going through the git history is way more of a PITA than a clear changelog. That's the reason people still use them.

**Comment by drewish** [comment]
What library? I'd love to be able to follow along there.

**Comment by envygeeks** [comment]
This was a bug in extras and is fixed as of now, it'll be released today or tomorrow.
