### ISSUE TITLE
Slugify multi word category

### ISSUE THREAD

**Issue by yguezeldal** [jekyll/jekyll-assets#358]
_Hope I am in the right repo here._

Currently if I have a post with this category in front matter:

```
category: "Multi word category"
```

and the permalinks configured like this:

```
permalink: /:categories/:title/
```

the output looks like this in the `_site` folder:

```
multi word category/post-title/index.html
multi-word-category/index.html
```

which is producing an ugly url for the post like this:

```
/multi%20word%20category/post-title/
```

It would be much better path when we could slugify multi word categories. Btw, it would be also more consistent with the multi word tags as they are slugifyed already.

**Comment by envygeeks** [comment]
hey @yguezeldal, this ticket should be filed on https://github.com/jekyll/jekyll/issues/new
