### ISSUE TITLE
Image resize, crop and quality in a single tag

### ISSUE THREAD

**Issue by ikus060** [jekyll/jekyll-assets#360]
Hello,

I'm using Jekkyl Asset for some time. I start experimenting to use multiple proxy on a single image like this:

`{% img "images/minarca/minarca-bg.jpg" magick:resize:1170x400^ magick:crop:1170x400 magick:quality:75 %}`

Is it only or this is not working ? In the end, the image generate is not resize or cropped. But the following is working as expected:

`{% img "images/minarca/minarca-bg.jpg" magick:resize:1170x400^ %}`

Any advice for me ?

**Comment by envygeeks** [comment]
It should work, we run every filter available, what happens if you quote each proxy?

**Comment by ikus060** [comment]
You mean like this:
`{% img "images/minarca/minarca-bg.jpg" "magick:resize:1170x400^" "magick:crop:1170x400" "magick:quality:75" %}`

Same result, the resulting image is not resized and not croped.

**Comment by envygeeks** [comment]
This test case is fixed in 3.x which will be released this upcomming week.
