### ISSUE TITLE
Cache is not invalidated by changes to Liquid variables

### ISSUE THREAD

**Issue by pgib** [jekyll/jekyll-assets#361]
This is kind of a tricky one, but if caching is enabled and one is using Liquid variables within the assets (e.g. a stylesheet), the assets are not rebuilt if the underlying data is different. Here's a simple example demonstrating the problem:

https://github.com/pgib/jekyll-assets-liquid-cache-issue

Example:

```scss
body
{
  background-color: {{ site.styles.background_color }};
}
```

`_config.yml`:

```yaml
styles:
  background_color: white
```

On the first build, the resulting stylesheet works fine, but on subsequent builds, the stylesheet does not get changed when the underlying data is updated.

**Comment by envygeeks** [comment]
We parse as middleware on Sprockets and we really have no control over the caches (other than removing all or none) in the case of Liquid.  I don't know if I can (or more so am willing to) fix this because the problem is largely out of our scope and belongs in the hands of Sprockets IMO.
