### ISSUE TITLE
What does automatic_img_resize do?

### ISSUE THREAD

**Issue by nmccrea** [jekyll/jekyll-assets#363]
I am trying to figure out what the automatic_img_resize configuration does. It is not explained in the documentation. My initial assumption was that it resizes images when they are imported to the site assets folder by jekyll-assets, but this does not seem to be the case. Any clarification would be super helpful.

Thanks.

**Comment by drewish** [comment]
It reads the image file and determines the dimensions and the adds height and width attributes to the `img` tag.
