### ISSUE TITLE
Add Example Sites to Wiki

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-assets#364]
@envygeeks Thoughts on adding a "Sites Using Jekyll Assets" to the Wiki? I've got an OSS example here: https://github.com/jhabdas/habd.as. And instructions on how to add this gem to allow peeps to hit PageSpeed 100 here: https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/#add-the-jekyll-assets-gem. LMK or just close.

**Comment by envygeeks** [comment]
Yeah I'm cool with that. Is the wiki open or do I need to open it?

**Comment by jhabdas** [comment]
Needs open

**Comment by envygeeks** [comment]
https://github.com/jekyll/jekyll-assets/wiki/Sites-Using-Jekyll-Assets
