### ISSUE TITLE
Uglify in Harmony / ES6 / ES2015

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-assets#365]
FYI this is a thing now: `3.0.4.harmony1`.

https://github.com/lautis/uglifier/issues/108#issuecomment-282484859

**Comment by jhabdas** [comment]
Reopening now that there's a tagged release in the repo. https://github.com/mishoo/UglifyJS2/releases/tag/harmony-v2.8.7

**Comment by jhabdas** [comment]
Might be seeing harmony release soon cut to NPM

**Comment by envygeeks** [comment]
We don't supply uglifier directly and instead rely on the Uglifier gem.  Please file this upstream with them and it will trickle down to us automatically (as we don't gemlock Uglify.)

https://github.com/lautis/uglifier

**Comment by jhabdas** [comment]
> We don't supply uglifier directly and instead rely on the Uglifier gem.

I'm aware of that. Which is why when I opened this issue I pointed at a version of the Uglifier gem I worked to have made to support Harmony modules before opening this issue.

> Please file this upstream with them and it will trickle down to us automatically (as we don't gemlock Uglify.)

I'm not sure it's going to be quite as simple as that. But maybe it will be. I opened a second issue for them given the initial issue linked above was created just to get the ball rolling last February.

https://github.com/lautis/uglifier/issues/119

**Comment by envygeeks** [comment]
@jhabdas do you mind shipping a pull request that updates our readme to show how to get support with the NPM stuff you did?

**Comment by jhabdas** [comment]
Been using Assets with ES6 for a little over a year now ([Gemfile](https://github.com/jhabdas/habd.as/blob/db057a71f76271a668ac50dee7e91fabb76e981b/Gemfile) here). There are some limitations, however, as the Uglifier is still evolving to better support the evolving TC39 spec. Next time I update my namesake blog I'll be sure to loop back and see what I can do to drive this forward. At the current I'm working on some Docker swarm stuff in relation to WP.

**Comment by jhabdas** [comment]
@envygeeks heard from @lautis and once uglifier harmonizes master you'll see the trickle down automatically based on current config. 👌
