### ISSUE TITLE
Unable to import bootstrap-sass and font-awesome-sass through jekyll-assets

### ISSUE THREAD

**Issue by cbsiddharth** [jekyll/jekyll-assets#367]
My project is using bootstrap and font-awesome and I am trying to import bootstrap-sass and font-awesome-sass through jekyll-assets. I'm unable to do so. I followed the [readme](https://github.com/jekyll/jekyll-assets#addons) and I have added both the gems into my Gemfile and `bundle` succeeded. in my main.scss file, I added  `@import 'bootstrap-sprockets'; @import 'bootstrap'` but got an error so had to split it into two lines with `@import 'bootstrap-sprockets';` and `@import 'bootstrap';` to get rid of this error. I Had to do the same for font-awesome as well. but after doing all this, when I build, I am getting some junk, 
```
      Generating...
                    楍牣獯景⁴刨 楗摮睯⁳捓楲瑰䠠獯⁴敖獲潩⁮⸵ㄸല䌊灯特杩瑨⠠⥃䴠捩潲潳瑦䌠牯潰慲楴湯‮汁⁬楲桧獴爠獥牥敶⹤਍਍湉異⁴牅潲㩲吠敨敲椠⁳潮映汩⁥硥整獮潩⁮湩∠㩃捜杹楷屮浴屰硥捥獪〲㜱㌰〱ㄭ㄰〰ㄭ摦汦㥲獪⸢਍
  Liquid Exception: 楍牣獯景⁴刨 楗摮睯⁳捓楲瑰䠠獯⁴敖獲潩⁮⸵ㄸല䌊灯特杩瑨⠠⥃䴠捩潲潳瑦䌠牯潰慲楴湯‮汁⁬楲桧獴爠獥牥敶⹤਍਍湉異⁴牅潲㩲吠敨敲椠⁳潮映汩⁥硥整獮潩⁮湩∠㩃捜杹楷屮浴屰硥捥獪〲㜱㌰〱ㄭ㄰〰ㄭ摦汦㥲獪⸢਍ in /_layouts/default.html
```
I tied locating some examples  on the internet that just imports these to gems and uses them but almost all of them include the whole sass source tree. I think I am going some obvious mistake. Any help is appreciated.

A small example or a write up will help me overcome this issue.

**Comment by envygeeks** [comment]
I'll add an example sometime but it's going to be the exact same thing I added before as multiple lines in a nicer block.  As far as the liquid exception is concerned, unless it says it originates from Jekyll Assets (in that we cache our own errors through Liquid) this error should be reported upstream so they can determine if it belongs here.
