### ISSUE TITLE
Feature request: Support bootstrap-rubygem

### ISSUE THREAD

**Issue by aaronwolen** [jekyll/jekyll-assets#369]
The ruby version of Bootstrap 4 is being developed under [bootstrap-rubygem](https://github.com/twbs/bootstrap-rubygem) rather than [bootstrap-sass](https://github.com/twbs/bootstrap-sass), which breaks jekyll-assets' super convenient method for importing bootstrap. I'd love to see support added for the new gem.

**Comment by armstrjare** [comment]
An easy fix is to:
```
mdkir _plugins
echo "require 'bootstrap'" > _plugins/jekyll-assets-bootstrap.rb
```

And make sure the `bootstrap` gem is in the Gemfile.

**Comment by envygeeks** [comment]
https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/addons/bootstrap.rb#L7 you are missing some steps to get it to work with Jekyll Assets.

**Comment by armstrjare** [comment]
Shouldn't need anything other than what I suggested.

**Comment by envygeeks** [comment]
This is supported in 3.x
