### ISSUE TITLE
Page specific css not compiled. 

### ISSUE THREAD

**Issue by looeee** [jekyll/jekyll-assets#372]
In `assets/css` I have a main.scss file which I include in the head with `{% css main %}`, which works as expected. However I want to include page specific css as well, so in the front matter I have:

```
css:
  'example'
```

and I have a corresponding `assets/css/example.scss`.

Now if I include `{% css example %}` under  `{% css main %}`, this gets compiled and included as expected. However, if I try to include it using {% css page.css %} (with the intention of including it conditionally), I get an error:

```
Regenerating: 1 file(s) changed at 2017-04-12 07:44:30                     Could not find the asset `page.css'
  Liquid Exception: Could not find the asset `page.css' in /_layouts/default.html
...error:
             Error: Could not find the asset `page.css'
             Error: Run jekyll build --trace for more information.
```

Is this a limitation of jekyll assets? or is there some way of including page specific css?

**Comment by cameronmcefee** [comment]
When you do `{% css page.css %}`, you're literally telling it to look for a file called `page.css`. If you want to pass it a variable value, I think you should be able to by writing it like `{% css '{{ page.css }}' %}`

**Comment by looeee** [comment]
Thanks for the suggestion, although it doesn't work (and neither do any other variations that I've tried). 

It is possible to include site variables in include tags in jekyll since [#1495](https://github.com/jekyll/jekyll/pull/1495) 
(like `{% include {{page.include}} %}`). 

It would be very useful to be able to do the same here. Or is there some other preferred manner of including page specific assets?

**Comment by looeee** [comment]
Thanks, I have got it to work. In full, the code is:

**Front Matter**
```
css:
  'example'
```

File called `example.scss` in the same directory as `main.scss`.

**Head include**

```
{% css main %}

{% if page.css %}
  {% for file in page.css %}
    {% css {{file}} %}
  {% endfor %}
{% endif %}
```

**Comment by cameronmcefee** [comment]
Ah, I guess I didn't know that nesting the filename turns it into an array. I assumed page.css was returning a string. I'm glad to hear you sorted it out.
