### ISSUE TITLE
Concatinate css with compiled scss

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll-assets#373]
From the readme docs, it looks like it isn't possible to concatinate css with a compiled scss file, correct? For example, if I wanted to merge bootstrap into my compiled css so only one file is required.

Previously I was compiling bootstrap from source into my stylesheet to get around this, but it adds about 2 seconds to the compile time. To get around this, I currently load the distribution version of bootstrap as a separate file in development and only compile it in during production builds. This requires some tricky include/exclude shenanigans, which is kind of ugly.

It'd be nice if I could just join distribution bootstrap with my compiled css as part of the asset pipeline. Does this exist and I missed it in the docs? Any cleaner hacks you can suggest?

**Comment by envygeeks** [comment]
Add bootstrap and then `/*\nrequire bootstrap\n*/`
