### ISSUE TITLE
Can't compile when site is in a folder with a space in the name

### ISSUE THREAD

**Issue by vincentritter** [jekyll/jekyll-assets#375]
Came across this by accident, but seems resolved by removing the 'jekyll-assets' gem. Please bear with me so I can explain. Unsure what is causing it, it might be a dependancy.

When using jekyll-assets on a project with the below file structure:
`~/Dev/Projects/MyJekyllProject/`

Executing 'bundle exec jekyll s' works without issue. However, if you use the below naming convention (notice the space in 'My Project'):
`~/Dev/My Projects/MyJekyllProject/`

executing the same above causes the following error:
`Liquid Exception: Could not locate the included file 'some-partial.html' in any of ["/Users/me/Dev/My", "Projects/MyJekyllProject/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/post.html`

You can see that it seems to build an array and splitting it at the space in `My Projects`.

Note that this affects macOS 10.12.5 (beta). I am looking at running a vanilla install and testing it on the latest public release (10.12.4). I will post findings, if different.

This is my first GitHub issue so if you need any more information I am happy to provide.

As mentioned, this issue is resolved after removing the jekyll-assets gem. Also, if it's a clue, this only started happening recently after doing a 'bundle update' - so perhaps again a dependancy might be the cause.

- System: macOS 10.12.5
- Jekyll (3.4.3)
- Jekyll-assets (2.2.8)

**Comment by kittsville** [comment]
I also started encountering this issue on Windows 7 when I added Jekyll Assets to my site.

The site generated fine but auto-regeneration caused the includes error you posted. GitHub Desktop clones projects into `{$user}/My Documents/GitHub/{$project_name}` so I'd imagine this has affected a few people.

- System: Windows 7 (SP1)
- Jekyll (3.4.3)
- Jekyll-assets (2.2.8)

**Comment by envygeeks** [comment]
This was related to Jekyll-Assets extra's gem, it's since been fixed so it should no longer be a problem.
