### ISSUE TITLE
Unknown tag 'img', Unknown tag 'js'

### ISSUE THREAD

**Issue by stevenmunro** [jekyll/jekyll-assets#376]
**_config.yml**
gems:
  - jekyll-assets

**Gemfile**
group :jekyll_plugins do
   gem "jekyll-assets"
end

jekyll version 3.4.3
Using jekyll-assets 0.4.1

Tags don't appear to be working. Am I overlooking something really simple here?

**Comment by stevenmunro** [comment]
ran bundle update
Installing jekyll-assets 2.2.8 (was 0.4.1)
fixed issue. 

Why on earth would installing jekyll-assets for the first time give me an old version?

**Comment by envygeeks** [comment]
That I honestly have no idea of :/ perhaps RubyGems temporarily had an error?

**Comment by faizanvahevaria** [comment]
@envygeeks 
I am getting the same error

Using jekyll-assets 3.0.5

**Comment by envygeeks** [comment]
Hey @faizanvahevaria 

This is out of my control.  Not only do I not control the RubyGems servers, or its API's but I do not control bundler and it's API or algorithms.  You'll need to file bugs on those respective repositories and ask them for further assistance, they are in control here.

**Comment by faizanvahevaria** [comment]
@envygeeks

I had to restart my computer.
It solved then.

Thanks for the response.
