### ISSUE TITLE
An error with an alt attribute

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-assets#377]
Hi there,

I have an issue using the image tag. In my source code I have (the alt is in Russian):

`{% image logo_3x.svg alt="Я люблю ИП" %}`

But it gets complied to:

```
<img src="/assets/logo_3x-e690e2c2d4ce9f428db46b55342ef8681f771825b0c37da6923b6dc232f09dc9.svg" alt="Я" люблю="" ИП="" width="108" height="27">
```

Is there any way to fix it?

jekyll 3.4.3
jekyll-assets 2.2.8

**Comment by envygeeks** [comment]
AFAIW this shouldn't be a problem as Cyrillic is UTF-8 (I don't remember if parts of it are UTF-16 but I don't think so.) I'll be working on this later this week so I'll take a look and see what's going on.

**Comment by vincentritter** [comment]
This also happens with English text and seems to be having problems when you use spaces in your Alt text. Probably upstream...

Example:
```
{% img me_bw.jpg height='auto' class='f-r' alt='this is my name' %}
```

This gets compiled as the following:
```
<img src="/assets/me_bw.jpg" height="auto" class="f-r" alt="this" is="" my="" name="" width="248">
```

**Comment by envygeeks** [comment]
After relooking at this issue it's because you are using `{% img alt="" %}` which is not supported in the 2.x branch, in 3.x we do support that syntax though.  If you plan to stick with 2.x please do `{% img path alt:"My value" %}`

**Comment by iloveip** [comment]
@envygeeks Thank you very much. How can I upgrade to 3.x branch?

**Comment by envygeeks** [comment]
@iloveip you will be able to upgrade this upcomming week when it's finished and released, Tuesday probably since I won't be available Monday.  It will ship with an upgrading doc that makes it super simple.

**Comment by iloveip** [comment]
@envygeeks Ok, thank you very much!
