### ISSUE TITLE
Missing images when building site

### ISSUE THREAD

**Issue by bstarr322** [jekyll/jekyll-assets#388]
Thanks for this plugin.

When I tried `bundle exec jekyll serve`, it says the following warnings,
`Configuration file: E:/projects/jekyll/renttrack/fork/www-marketing/_config.yml
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
DEPRECATION WARNING: You are using the a deprecated processor interface Jekyll::Assets::Addons::Processors::Liquid.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <top (required)> at C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-assets-2.1.3/lib/jekyll/assets/addons/processors/liquid.rb:30)
            Source: E:/projects/jekyll/renttrack/fork/www-marketing
       Destination: E:/projects/jekyll/renttrack/fork/www-marketing/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 11.785 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'E:/projects/jekyll/renttrack/fork/www-marketing'
Configuration file: E:/projects/jekyll/renttrack/fork/www-marketing/_config.yml
    Server address: http://127.0.0.1:9001/
  Server running... press ctrl-c to stop.`

I 'd like to know  how to fix this issue.
All styles & scripts are rendered properly, but some images are not.
The images that I included in css (background-image) are not rendered properly.
ex;` background: url(asset_path('gradient-angle.png')) no-repeat center;`
it says it can't find `gradient-angle.png`.

jekyll (3.0.5)
jekyll-assets (2.1.3)

Thanks in advance !

**Comment by envygeeks** [comment]
We know. Thanks.

**Comment by bstarr322** [comment]
@envygeeks  sorry, but how to fix it ?
no way to fix it ?

**Comment by envygeeks** [comment]
As far as your missing images you'll need to provide more information.

**Comment by bstarr322** [comment]
This is not working. of course i am sure I have `gradient-angle.png` in `_assets/img` folder.

An example of using Liquid in your SCSS:
`.bg {
  background: url(asset_path('gradient-angle.png'));
}`

**Comment by bstarr322** [comment]
@envygeeks  any idea ?

**Comment by HaoZeke** [comment]
What you need to do is follow the sprockets specification...
image-url("SKA_night.jpg")

.bg { background: image-url('gradient-angle.png'); }

**Comment by bstarr322** [comment]
@HaoZeke 
Would you please share the version of Jekyll & assets plugin ?

**Comment by envygeeks** [comment]
This is fixed in v3.0.0 which will be released this week.  We've improved the way we work with Sprockets.

**Comment by bstarr322** [comment]
Thanks, @envygeeks
