### ISSUE TITLE
Intro docs assume Rails ecosystem familiarity

### ISSUE THREAD

**Issue by antgel** [jekyll/jekyll-assets#389]
I'm referring to:
> Jekyll assets is an asset pipeline using Sprockets 3 to build specifically for Jekyll. It utilizes new features of both Sprockets and Jekyll to try and achieve a clean and extensible assets platform.

As a naive Jekyll user, I don't find this helpful. Let's say I know nothing about Rails - I have to go and find out what is an asset pipeline or platform / Liquid / Sprockets / Bower / etc.

It would be nice if the intro explained what jekyll-assets did, in terms of the use case, before diving into (relative) detail. What problem does jekyll-assets solve, and why might I want to use it?

**Comment by envygeeks** [comment]
If you don't know what an asset pipeline is then you probably don't need one. This project does not serve as an introduction to how to manage assets for the internet, it simply helps you manage those assets. Yes, you do need to know what Sprockets is, yes you do need to know what Bower is, it is not my job to explain to you what they are, it was only a goal to enable you the ability to use them through our system.  They do a plenty good job to explaining themselves, on their own.

If you feel there could be a better explanation, please feel free to file a pull request and I'll consider it much more deeply than a ticket, I encourage people to improve our documentation and often accept pull requests for it without question as long as the English is fairly decent, however... past that, Jekyll-Assets is a developer/designer tool, and developers should know what problem Jekyll Assets solves and the tools it use, or they wouldn't have sought it out.

I look forward to your pull request.

**Comment by antgel** [comment]
We'll have to agree to disagree on the "if you don't know what it is, you don't need one". Nice slogan, but borderline elitist, I might well need this but I don't know what it does, so ho hum. I'm disappointed by the overall tone of the response, which goes somewhat against:

> If you do not understand something in our documentation please feel free to file a ticket and it will be explained and the documentation updated

I'm not suggesting that the docs include explanations of what every sub-tool (Sprockets / Bower etc) does, but I am suggesting that they start with a short sentence or two explaining what functionality is provided and / or problems are solved.

**Comment by envygeeks** [comment]
I'm not trying to be elitist, I do not wish to be as I do not think I'm better than anybody, but I do know that I don't know how to explain things to the average user, as most of what I do is tailored for developers.  This is why I ask people to ship pull requests if they can explain it to the average user better than I could.

I don't disagree with what you want (not not anyways, as over the last few months I've slowly come to terms with how bad my documentation is for non-developers and started trying to improve it -- not in this repository but in others,) but it's still hard when you're a developer, who develops for developers.
