### ISSUE TITLE
Using img tags in Markdown posts [Kramdown]

### ISSUE THREAD

**Issue by HaoZeke** [jekyll/jekyll-assets#394]
Hi, so using 
{% img waterfall class="img-fluid" alt:'Waterfall' %}

works in html files, but when I use it in a post, (a markdown formatted post)

Then I get 

<img src=”/assets/waterfall-db00fd724e12d809173b0539c2b23c1bd1ac68a7f40114ab73aed1ea113e4830.jpg” class=img-fluid alt=”Waterfall” width=”1883” height=”1638”>

Which is actually NOT html because markdown has converted it to

<p>&lt;img src=”/assets/waterfall-db00fd724e12d809173b0539c2b23c1bd1ac68a7f40114ab73aed1ea113e4830.jpg” class=img-fluid alt=”Waterfall” width=”1883” height=”1638”&gt;</p>

ie. <> became &lt &gt

I know this doesn't happen with redcarpet, but is there any way to get kramdown to correctly use the img tag?

**Comment by envygeeks** [comment]
Hi @HaoZeke questions about Kramdown should be asked to the Kramdown developers, and questions about Jekyll should be asked at https://talk.jekyllrb.com.  I'm sorry to do this but this medium must be kept for issues only.

**Comment by HaoZeke** [comment]
Actually it's about the specific liquid tag from jekyll-assets...
Regular classes and HTML markup works fine.
