### ISSUE TITLE
Front matter causes imports to fail

### ISSUE THREAD

**Issue by chrisfinazzo** [jekyll/jekyll-assets#401]
The presence of front-matter marks in my main SCSS file is causing my imports to fail. If I remove these lines, or comment them out, everything works as it should. 

Jekyll 3.4 + Jekyll Assets 2.3.2.

    ---

    ---
    
    @import "variables";
    @import "grid";

    body {
      line-height: 1.6;
      font-size: 18px;
    }
 
    h1, h2, h3 {
      line-height: 1.2;
    }

    .social ul {
      list-style-type: none;
      text-align: center;
     }

    .social ul li {
      display: inline;
    }

    .social ul li a {
      text-decoration: none;
    }

    .rights {
      text-align: center;
    }

**Comment by envygeeks** [comment]
This is desired and intentional behavior.  We have never supported Front-Matter and probably never will because there is no reason for it in our asset system (and technically there is no need for it in Jekyll's either since it could clearly designate a default asset folder that we could share.)

**Comment by chrisfinazzo** [comment]
Yeah, it's the one exception in the documentation.
