### ISSUE TITLE
Sass liquid tags not working?

### ISSUE THREAD

**Issue by RNCTX** [jekyll/jekyll-assets#402]
So I just set up image_optim and going by the digested images showing up in the /assets folder it is working fine.  Naturally I want to put those in the CSS for things like backgrounds and overlays too, since I am processing *all* images.

`&:before {
                        @include vendor('transition', 'background-color #{_duration(bg)} ease-in-out');
                        @include vendor('transition-delay', '#{_duration(intro)}');
                        background-image: linear-gradient(to top, #{_palette(bg-overlay)}, #{_palette(bg-overlay)}), url(/assets/("{{ site.overlay }}"));
...
}`

Produces the following css....

`background-image: linear-gradient(to top, rgba(19,21,25,0.5), rgba(19,21,25,0.5)),url(/assets/"{{ site.overlay }}");`

This is straight off of the readme, I can't find a whole lot of other documentation on image tags but I'm assuming that since this is a site variable it has to be defined?  I have `overlay: overlay.png` in my _config.yml.

Am I missing something?

edit: nevermind, found the included (asset_path) and (asset_logical_name) SCSS variables, fixed my syntax and all is well, thanks for the great plugin!

**Comment by RNCTX** [comment]
Nevermind, found other docs pointing out my misunderstanding of the syntax.  I found the (asset_path) and (asset_logical_name) SCSS variables.

**Comment by RNCTX** [comment]
Reopened at your request.

relevant config...

`# Build settings
markdown: kramdown

exclude:
 - Gemfile
 - Gemfile.lock
 - s3_website.yml
 - asset-cache
 - drafts

# Collections
# Add new menu panels as HTML or md files inside the _panels folder with a head tag of 'homemenu'
collections:
 - panels

# ruby gems
gems:
  - font-awesome-sass
  - jekyll-assets
  - match_regex
  - uglifier
  - sass

assets:
  compress:
    css: true
    js: true

  #

  autowrite: true
  cache: asset-cache
  cache_type: filesystem
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: false

  #
  assets:
    - "*.png"
    - "*.PNG"
    - "*.jpg"
    - "*.jpeg"
    - "*.JPEG"
    - "*.JPG"
    - "main.css"
    - "noscript.css"
    - "main.js"
    - "*.scss"

  sources:
    - _assets/css
    - _assets/sass
    - _panels
    - _assets/stylesheets
    - _assets/font-awesome
    - _assets/js
    - _assets/images

  #

  features:
    liquid: true
    integrity: false
    automatic_img_size: false
    automatic_img_alt : false`

**Comment by envygeeks** [comment]
This should be fixed in 3.x.
