### ISSUE TITLE
_/site/assets folder contains old css files

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#409]
When I update the CSS, Jekyll causes a new version to be put in the `_site/assets` folder. However the old file remains, so quite quickly if I make several changes and hit save, I end up with several CSS files inside that folder. How come the old file is not removed?

**Comment by envygeeks** [comment]
The reason we don't is because before we never took full advantage of the manifest, in 3.x we do so this will not be the case with 3.x.  Yes, it can fill up the disk with small files but doing that on each run also adds to our overhead in 2.x which was already slow because of Sprockets.

**Comment by envygeeks** [comment]
This is fixed in 3.x
