### ISSUE TITLE
Sub assets key?

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#410]
In the documentation you have:
~~~
assets:
    assets:
      - "*.png"
      - "bundle.css"
~~~
What does this mean?

I thought it might be a way to make it build assets that have not been requested.. As noticed that Jekyll Assets only compiles assets that have been requested in the HTML or CSS. E.g. if I have an a bunch of PNG's they are only moved into `_site/assets` if I use those images.

**Comment by envygeeks** [comment]
Please provide more debugging information.

**Comment by envygeeks** [comment]
This is because Sprockets optimized itself, you now need to provide a more valid and contextual name, like "ubuntu" or "ubuntu.png".  This is out of my control, and unfortunately I do not wish to implement this feature as we mostly like to rely on Sprockets to do the heavy lifting.
