### ISSUE TITLE
Sass options ignored

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#411]
After switching to using this plugin my Sass options are now ignored.
~~~
sass:
  style: nested
  line_numbers: true
  sourcemap: file
~~~
The outputted css file is not nested and has no sourcemap.

**Comment by envygeeks** [comment]
This isn't Jekyll.

**Comment by iamdriz** [comment]
@envygeeks How do I print out line numbers, change the style and build source maps using the gem?

**Comment by envygeeks** [comment]
Sourcemaps are coming with 3.x, other options will probably remain unsupported as I don't have enough time to implement said features as nobody is sponsoring this project, and we have very little contributions (though we do have one person who does so besides me.)

**Comment by envygeeks** [comment]
SourceMaps are implemented.
