### ISSUE TITLE
Font Awesome breaks when using assets

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#412]
When adding in all files to be compiled. e.g.
~~~
assets:
 - "*"
~~~
It causes the error: `jekyll 3.5.2 | Error:  Undefined variable: "$fa-css-prefix".`

Removing it fixes it, however it then means that not all files are compiled automatically by the sprockets and only files that are explicitly called.

**Comment by envygeeks** [comment]
This is a problem with one of your SASS files AFAICT.
