### ISSUE TITLE
Asset path can't find video

### ISSUE THREAD

**Issue by iamdriz** [jekyll/jekyll-assets#423]
I have the following MP4 in my assets folder:

`_assets/video/home.mp4`

And I'm trying to include it in my page like so:

`<video src="{% asset_path video/home.mp4 %}">`

But I'm getting the error:
~~~
Could not find the asset `video/home.mp4'
  Liquid Exception: Could not find the asset `video/home.mp4' in index.html
~~~

That folder is in my assets sources key:
~~~
assets:
    sources:
        - _assets/css
        - _assets/img
        - _assets/js
        - _assets/video
~~~

**Comment by envygeeks** [comment]
Try 'home.mp4' there is no guranteed support for Video at all in 2.x, it was never designed for video.  If you wish for video it will be available in 3.x when it's released.

Thanks!

**Comment by envygeeks** [comment]
Actully, I'm going to leave this open to remind me to add a video folder.

**Comment by iamdriz** [comment]
What do you mean by try `home.mp4`? Do you mean remove the `video/` prefix?
The file itself isn't copied across to `assets` so the URL pattern for `asset_path` shouldn't matter.
Thanks!

**Comment by envygeeks** [comment]
I wrote Jekyll-Assets 2.x, I'm pretty sure I know how my software works. And having the prefix doesn't work by my own design.  There is no "video" folder to Sprockets unless it's "_assets/video/video"
