### ISSUE TITLE
Liquid syntax error: Expected end_of_string but found id in 

### ISSUE THREAD

**Issue by mayankpant11** [jekyll/jekyll-assets#425]
Hi
Getting an error 
Liquid syntax error: Expected end_of_string but found id in "{{Data.RatePlanCharge[0].ChargedThroughDate Date| date: "%s" | plus : 86400 | date: "%Y-%m-%d" |to_json}}"

Please help

**Comment by envygeeks** [comment]
This is Jekyll Assets, not Jekyll. Please file your issue at https://github.com/jekyll/jekyll
