### ISSUE TITLE
Inherit Jekyll's Rubocop config

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-assets#426]
👋  Are you interested in following Rubocop's config from upstream?

Should I start a PR and submit auto-corrected offenses and list remaining offenses in `.rubocop.yml` as we do on Jekyll?

**Comment by envygeeks** [comment]
I would like to but Jekyll's own coding standards diverge from mine in quite a few places.  Where my repository is moving towards enforcing some things, Jekyll's remains the same. Where my repositories in enforce some things, Jekyll doesn't.  Aside from that most of my repositories do already use a standard ".rubocop.yml" that is shared across all of them, I'll make sure to update this one and start fixing violations (which we already track in CodeClimate.)

**Comment by DirtyF** [comment]
It would be nice if we agreed on some common conventions, as matter of fact I am strongly unopiniated when it comes to Ruby. 

We're thinking of adding more from the latest cops, feel free to share your insight if you care: https://github.com/jekyll/jekyll/pull/6470

**Comment by envygeeks** [comment]
hey @DirtyF I've updated my ruleset and applied it: https://github.com/jekyll/jekyll-assets/blob/master/.rubocop.yml that's pretty much where I stand with the way I write Ruby.
