### ISSUE TITLE
How to install 3.0?

### ISSUE THREAD

**Issue by Kuzirashi** [jekyll/jekyll-assets#436]
How to install jekyll-assets 3.0? By default it installs 2.4.0.

**Comment by envygeeks** [comment]
Hey @Kuzirashi, sorry I lost my laptop yesterday and had to setup an old one so I'm a day behind.

You can install the alpha with:

```ruby
gem "jekyll-assets", git: "https://github.com/jekyll/jekyll-assets.git", group: :jekyll_plugins
```

**Comment by Kuzirashi** [comment]
Thank you 👍  :)

And thank you for work on this project! It's rock solid! : )
